export const demographicsData = [
    // Dummy Patient 1
    {
        patient: {
            chartNumber: 1,
            firstName: 'Terry',
            midInitial: 'B',
            lastName: 'Daniels',
            dateOfBirth: '01/14/1993',
            SSN: '223-54-7689',
            street1: '123 Baker Rd.',
            street2: '',
            city: 'Nashville',
            state: 'TN',
            zipCode: '23765',
            homePhone: '(123)-456-7897',
            workPhone: '(123)-456-7291',
            cellPhone: '',
            email: 'TBDan@gmail.com',
        },
        responsibleParty: {
            chartNumber: 1,
            respFirstName: '',
            respLastName: '',
            respMI: '',
            respDateOfBirth: '',
            respSSN: '',
            respHomePhone: '',
            respWorkPhone: '',
            respCellPhone: '',
            respStreet1: '',
            respStret2: '',
            respCity: '',
            respState: '',
            respZipCode: '',
            respEmail: '',
        },
        insurance1: {
            chartNumber: 1,
            ins1Code: '',
            ins1Name: '',
            ins1Street1: '',
            ins1Street2: '',
            ins1City: '',
            ins1State: '',
            ins1ZipCode: '',
            ins1Phone: '',
            ins1MemberNo: '',
            ins1GroupName: '',
            Ins1GroupNumber: '',
            ins1Ded: #,
        },
        insurance2: {
            chartNumber: 1,
            ins2Code: '',
            ins2Name: '',
            ins2Street1: '',
            ins2Street2: '',
            ins2City: '',
            ins2State: '',
            ins2ZipCode: '',
            ins2Phone: '',
            ins2MemberNo: '',
            ins2GroupName: '',
            Ins2GroupNumber: '',
            ins2Ded: #,
        }
    },
    // Dummy Patient 2
    {
        patient: {
            chartNumber: 2,
            firstName: '',
            midInitial: '',
            lastName: '',
            dateOfBirth: '',
            SSN: '',
            street1: '',
            street2: '',
            city: '',
            state: '',
            zipCode: '',
            homePhone: '',
            workPhone: '',
            cellPhone: '',
            email: '',
        },
        responsibleParty: {
            chartNumber: 2,
            respFirstName: '',
            respLastName: '',
            respMI: '',
            respDateOfBirth: '',
            respSSN: '',
            respHomePhone: '',
            respWorkPhone: '',
            respCellPhone: '',
            respStreet1: '',
            respStret2: '',
            respCity: '',
            respState: '',
            respZipCode: '',
            respEmail: '',
        },
        insurance1: {
            chartNumber: 2,
            ins1Code: '',
            ins1Name: '',
            ins1Street1: '',
            ins1Street2: '',
            ins1City: '',
            ins1State: '',
            ins1ZipCode: '',
            ins1Phone: '',
            ins1MemberNo: '',
            ins1GroupName: '',
            Ins1GroupNumber: '',
            ins1Ded: #,
        },
        insurance2: {
            chartNumber: 2,
            ins2Code: '',
            ins2Name: '',
            ins2Street1: '',
            ins2Street2: '',
            ins2City: '',
            ins2State: '',
            ins2ZipCode: '',
            ins2Phone: '',
            ins2MemberNo: '',
            ins2GroupName: '',
            Ins2GroupNumber: '',
            ins2Ded: #,
        }
    },
    // Dummy Patient 3
    {
        patient: {
            chartNumber: 3,
            firstName: '',
            midInitial: '',
            lastName: '',
            dateOfBirth: '',
            SSN: '',
            street1: '',
            street2: '',
            city: '',
            state: '',
            zipCode: '',
            homePhone: '',
            workPhone: '',
            cellPhone: '',
            email: '',
        },
        responsibleParty: {
            chartNumber: 3,
            respFirstName: '',
            respLastName: '',
            respMI: '',
            respDateOfBirth: '',
            respSSN: '',
            respHomePhone: '',
            respWorkPhone: '',
            respCellPhone: '',
            respStreet1: '',
            respStret2: '',
            respCity: '',
            respState: '',
            respZipCode: '',
            respEmail: '',
        },
        insurance1: {
            chartNumber: 3,
            ins1Code: '',
            ins1Name: '',
            ins1Street1: '',
            ins1Street2: '',
            ins1City: '',
            ins1State: '',
            ins1ZipCode: '',
            ins1Phone: '',
            ins1MemberNo: '',
            ins1GroupName: '',
            Ins1GroupNumber: '',
            ins1Ded: #,
        },
        insurance2: {
            chartNumber: 3,
            ins2Code: '',
            ins2Name: '',
            ins2Street1: '',
            ins2Street2: '',
            ins2City: '',
            ins2State: '',
            ins2ZipCode: '',
            ins2Phone: '',
            ins2MemberNo: '',
            ins2GroupName: '',
            Ins2GroupNumber: '',
            ins2Ded: #,
        }
    },
    // Dummy Patient 4
    {
        patient: {
            chartNumber: 4,
            firstName: '',
            midInitial: '',
            lastName: '',
            dateOfBirth: '',
            SSN: '',
            street1: '',
            street2: '',
            city: '',
            state: '',
            zipCode: '',
            homePhone: '',
            workPhone: '',
            cellPhone: '',
            email: '',
        },
        responsibleParty: {
            chartNumber: 4,
            respFirstName: '',
            respLastName: '',
            respMI: '',
            respDateOfBirth: '',
            respSSN: '',
            respHomePhone: '',
            respWorkPhone: '',
            respCellPhone: '',
            respStreet1: '',
            respStret2: '',
            respCity: '',
            respState: '',
            respZipCode: '',
            respEmail: '',
        },
        insurance1: {
            chartNumber: 4,
            ins1Code: '',
            ins1Name: '',
            ins1Street1: '',
            ins1Street2: '',
            ins1City: '',
            ins1State: '',
            ins1ZipCode: '',
            ins1Phone: '',
            ins1MemberNo: '',
            ins1GroupName: '',
            Ins1GroupNumber: '',
            ins1Ded: #,
        },
        insurance2: {
            chartNumber: 4,
            ins2Code: '',
            ins2Name: '',
            ins2Street1: '',
            ins2Street2: '',
            ins2City: '',
            ins2State: '',
            ins2ZipCode: '',
            ins2Phone: '',
            ins2MemberNo: '',
            ins2GroupName: '',
            Ins2GroupNumber: '',
            ins2Ded: #,
        }
    },
    // Dummy Patient 5
    {
        patient: {
            chartNumber: 5,
            firstName: '',
            midInitial: '',
            lastName: '',
            dateOfBirth: '',
            SSN: '',
            street1: '',
            street2: '',
            city: '',
            state: '',
            zipCode: '',
            homePhone: '',
            workPhone: '',
            cellPhone: '',
            email: '',
        },
        responsibleParty: {
            chartNumber: 5,
            respFirstName: '',
            respLastName: '',
            respMI: '',
            respDateOfBirth: '',
            respSSN: '',
            respHomePhone: '',
            respWorkPhone: '',
            respCellPhone: '',
            respStreet1: '',
            respStret2: '',
            respCity: '',
            respState: '',
            respZipCode: '',
            respEmail: '',
        },
        insurance1: {
            chartNumber: 5,
            ins1Code: '',
            ins1Name: '',
            ins1Street1: '',
            ins1Street2: '',
            ins1City: '',
            ins1State: '',
            ins1ZipCode: '',
            ins1Phone: '',
            ins1MemberNo: '',
            ins1GroupName: '',
            Ins1GroupNumber: '',
            ins1Ded: #,
        },
        insurance2: {
            chartNumber: 5,
            ins2Code: '',
            ins2Name: '',
            ins2Street1: '',
            ins2Street2: '',
            ins2City: '',
            ins2State: '',
            ins2ZipCode: '',
            ins2Phone: '',
            ins2MemberNo: '',
            ins2GroupName: '',
            Ins2GroupNumber: '',
            ins2Ded: #,
        }
    },
]