export const documentsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    documentType: "Medical Report",
    documentName: "Blood Test Results",
    documentDate: "2024-08-10",
    documentPath: "/documents/1/blood_test_results.pdf",
    encounterNumber: "E001",
  },
  {
    chartNumber: 1,
    documentType: "X-Ray",
    documentName: "Chest X-Ray",
    documentDate: "2024-08-11",
    documentPath: "/documents/1/chest_xray.pdf",
    encounterNumber: "E002",
  },
  {
    chartNumber: 1,
    documentType: "Prescription",
    documentName: "Painkillers Prescription",
    documentDate: "2024-08-12",
    documentPath: "/documents/1/painkillers_prescription.pdf",
    encounterNumber: "E003",
  },
  {
    chartNumber: 1,
    documentType: "Lab Results",
    documentName: "Blood Test Report",
    documentDate: "2024-05-01",
    documentPath: "/documents/1/blood_test_report.pdf",
    encounterNumber: "E004",
  },
  {
    chartNumber: 1,
    documentType: "Prescription",
    documentName: "Antibiotics",
    documentDate: "2024-05-03",
    documentPath: "/documents/1/antibiotics.pdf",
    encounterNumber: "E005",
  },
  {
    chartNumber: 1,
    documentType: "Referral",
    documentName: "Orthopedic Specialist",
    documentDate: "2024-05-06",
    documentPath: "/documents/1/orthopedic_referral.pdf",
    encounterNumber: "E006",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    documentType: "Medical Report",
    documentName: "Annual Physical Exam",
    documentDate: "2024-07-01",
    documentPath: "/documents/2/annual_physical_exam.pdf",
    encounterNumber: "E007",
  },
  {
    chartNumber: 2,
    documentType: "Lab Results",
    documentName: "Urine Test",
    documentDate: "2024-07-05",
    documentPath: "/documents/2/urine_test.pdf",
    encounterNumber: "E008",
  },
  {
    chartNumber: 2,
    documentType: "Prescription",
    documentName: "Antibiotics Prescription",
    documentDate: "2024-07-07",
    documentPath: "/documents/2/antibiotics_prescription.pdf",
    encounterNumber: "E009",
  },
  {
    chartNumber: 2,
    documentType: "X-Ray",
    documentName: "Chest X-Ray",
    documentDate: "2024-05-10",
    documentPath: "/documents/2/chest_xray.pdf",
    encounterNumber: "E010",
  },
  {
    chartNumber: 2,
    documentType: "Medical Report",
    documentName: "Annual Physical Exam",
    documentDate: "2024-05-12",
    documentPath: "/documents/2/annual_physical_report.pdf",
    encounterNumber: "E011",
  },
  {
    chartNumber: 2,
    documentType: "Lab Results",
    documentName: "Cholesterol Screening",
    documentDate: "2024-05-14",
    documentPath: "/documents/2/cholesterol_screening.pdf",
    encounterNumber: "E012",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    documentType: "Medical Report",
    documentName: "Eye Examination",
    documentDate: "2024-06-15",
    documentPath: "/documents/3/eye_examination.pdf",
    encounterNumber: "E013",
  },
  {
    chartNumber: 3,
    documentType: "X-Ray",
    documentName: "Dental X-Ray",
    documentDate: "2024-06-17",
    documentPath: "/documents/3/dental_xray.pdf",
    encounterNumber: "E014",
  },
  {
    chartNumber: 3,
    documentType: "Prescription",
    documentName: "Glasses Prescription",
    documentDate: "2024-06-20",
    documentPath: "/documents/3/glasses_prescription.pdf",
    encounterNumber: "E015",
  },
  {
    chartNumber: 3,
    documentType: "Medical Report",
    documentName: "Cardiology Consultation",
    documentDate: "2024-05-18",
    documentPath: "/documents/3/cardiology_consultation.pdf",
    encounterNumber: "E016",
  },
  {
    chartNumber: 3,
    documentType: "Prescription",
    documentName: "Blood Pressure Medication",
    documentDate: "2024-05-20",
    documentPath: "/documents/3/blood_pressure_medication.pdf",
    encounterNumber: "E017",
  },
  {
    chartNumber: 3,
    documentType: "X-Ray",
    documentName: "Spine X-Ray",
    documentDate: "2024-05-22",
    documentPath: "/documents/3/spine_xray.pdf",
    encounterNumber: "E018",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    documentType: "Medical Report",
    documentName: "EKG Results",
    documentDate: "2024-05-10",
    documentPath: "/documents/4/ekg_results.pdf",
    encounterNumber: "E019",
  },
  {
    chartNumber: 4,
    documentType: "X-Ray",
    documentName: "Abdominal X-Ray",
    documentDate: "2024-05-12",
    documentPath: "/documents/4/abdominal_xray.pdf",
    encounterNumber: "E020",
  },
  {
    chartNumber: 4,
    documentType: "Prescription",
    documentName: "Blood Pressure Medication",
    documentDate: "2024-05-15",
    documentPath: "/documents/4/blood_pressure_medication.pdf",
    encounterNumber: "E021",
  },
  {
    chartNumber: 4,
    documentType: "Lab Results",
    documentName: "Diabetes Screening",
    documentDate: "2024-05-25",
    documentPath: "/documents/4/diabetes_screening.pdf",
    encounterNumber: "E022",
  },
  {
    chartNumber: 4,
    documentType: "Medical Report",
    documentName: "Pulmonary Function Test",
    documentDate: "2024-05-28",
    documentPath: "/documents/4/pulmonary_function_test.pdf",
    encounterNumber: "E023",
  },
  {
    chartNumber: 4,
    documentType: "Referral",
    documentName: "Dermatology Specialist",
    documentDate: "2024-05-30",
    documentPath: "/documents/4/dermatology_referral.pdf",
    encounterNumber: "E024",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    documentType: "Medical Report",
    documentName: "MRI Results",
    documentDate: "2024-04-25",
    documentPath: "/documents/5/mri_results.pdf",
    encounterNumber: "E025",
  },
  {
    chartNumber: 5,
    documentType: "X-Ray",
    documentName: "Hand X-Ray",
    documentDate: "2024-04-27",
    documentPath: "/documents/5/hand_xray.pdf",
    encounterNumber: "E026",
  },
  {
    chartNumber: 5,
    documentType: "Prescription",
    documentName: "Vitamin D Supplements",
    documentDate: "2024-04-30",
    documentPath: "/documents/5/vitamin_d_supplements.pdf",
    encounterNumber: "E027",
  },
  {
    chartNumber: 5,
    documentType: "Medical Report",
    documentName: "MRI Results",
    documentDate: "2024-04-25",
    documentPath: "/documents/5/mri_results.pdf",
    encounterNumber: "E028",
  },
  {
    chartNumber: 5,
    documentType: "X-Ray",
    documentName: "Hand X-Ray",
    documentDate: "2024-04-27",
    documentPath: "/documents/5/hand_xray.pdf",
    encounterNumber: "E029",
  },
  {
    chartNumber: 5,
    documentType: "Prescription",
    documentName: "Vitamin D Supplements",
    documentDate: "2024-04-30",
    documentPath: "/documents/5/vitamin_d_supplements.pdf",
    encounterNumber: "E030",
  },
  {
    chartNumber: 6,
    documentType: "Lab Results",
    documentName: "Thyroid Panel",
    documentDate: "2024-06-01",
    documentPath: "/documents/6/thyroid_panel.pdf",
    encounterNumber: "E031",
  },
  {
    chartNumber: 6,
    documentType: "Medical Report",
    documentName: "Neurology Consultation",
    documentDate: "2024-06-03",
    documentPath: "/documents/6/neurology_consultation.pdf",
    encounterNumber: "E032",
  },
  {
    chartNumber: 6,
    documentType: "Prescription",
    documentName: "Cholesterol Medication",
    documentDate: "2024-06-05",
    documentPath: "/documents/6/cholesterol_medication.pdf",
    encounterNumber: "E033",
  },
  {
    chartNumber: 6,
    documentType: "X-Ray",
    documentName: "Knee X-Ray",
    documentDate: "2024-06-07",
    documentPath: "/documents/6/knee_xray.pdf",
    encounterNumber: "E034",
  },
  {
    chartNumber: 6,
    documentType: "Referral",
    documentName: "Gastroenterology Specialist",
    documentDate: "2024-06-09",
    documentPath: "/documents/6/gastroenterology_referral.pdf",
    encounterNumber: "E035",
  },
  {
    chartNumber: 6,
    documentType: "Medical Report",
    documentName: "Physical Therapy Plan",
    documentDate: "2024-06-11",
    documentPath: "/documents/6/physical_therapy_plan.pdf",
    encounterNumber: "E036",
  },
  {
    chartNumber: 7,
    documentType: "Prescription",
    documentName: "Allergy Medication",
    documentDate: "2024-06-15",
    documentPath: "/documents/7/allergy_medication.pdf",
    encounterNumber: "E037",
  },
  {
    chartNumber: 7,
    documentType: "Lab Results",
    documentName: "Complete Blood Count",
    documentDate: "2024-06-17",
    documentPath: "/documents/7/complete_blood_count.pdf",
    encounterNumber: "E038",
  },
  {
    chartNumber: 7,
    documentType: "X-Ray",
    documentName: "Shoulder X-Ray",
    documentDate: "2024-06-19",
    documentPath: "/documents/7/shoulder_xray.pdf",
    encounterNumber: "E039",
  },
  {
    chartNumber: 7,
    documentType: "Medical Report",
    documentName: "Annual Wellness Check",
    documentDate: "2024-06-21",
    documentPath: "/documents/7/annual_wellness_check.pdf",
    encounterNumber: "E040",
  },
  {
    chartNumber: 7,
    documentType: "Referral",
    documentName: "Cardiology Specialist",
    documentDate: "2024-06-23",
    documentPath: "/documents/7/cardiology_referral.pdf",
    encounterNumber: "E041",
  },
  {
    chartNumber: 7,
    documentType: "Prescription",
    documentName: "Pain Reliever",
    documentDate: "2024-06-25",
    documentPath: "/documents/7/pain_reliever.pdf",
    encounterNumber: "E042",
  },
  {
    chartNumber: 8,
    documentType: "Medical Report",
    documentName: "Dermatology Follow-Up",
    documentDate: "2024-07-01",
    documentPath: "/documents/8/dermatology_follow_up.pdf",
    encounterNumber: "E043",
  },
  {
    chartNumber: 8,
    documentType: "Lab Results",
    documentName: "Lipid Profile",
    documentDate: "2024-07-03",
    documentPath: "/documents/8/lipid_profile.pdf",
    encounterNumber: "E044",
  },
  {
    chartNumber: 8,
    documentType: "X-Ray",
    documentName: "Ankle X-Ray",
    documentDate: "2024-07-05",
    documentPath: "/documents/8/ankle_xray.pdf",
    encounterNumber: "E045",
  },
  {
    chartNumber: 8,
    documentType: "Referral",
    documentName: "Endocrinology Specialist",
    documentDate: "2024-07-07",
    documentPath: "/documents/8/endocrinology_referral.pdf",
    encounterNumber: "E046",
  },
  {
    chartNumber: 8,
    documentType: "Prescription",
    documentName: "Diabetes Medication",
    documentDate: "2024-07-09",
    documentPath: "/documents/8/diabetes_medication.pdf",
    encounterNumber: "E047",
  },
  {
    chartNumber: 8,
    documentType: "Medical Report",
    documentName: "Surgery Follow-Up",
    documentDate: "2024-07-11",
    documentPath: "/documents/8/surgery_follow_up.pdf",
    encounterNumber: "E048",
  },
  {
    chartNumber: 9,
    documentType: "Lab Results",
    documentName: "Renal Function Panel",
    documentDate: "2024-07-15",
    documentPath: "/documents/9/renal_function_panel.pdf",
    encounterNumber: "E049",
  },
  {
    chartNumber: 9,
    documentType: "X-Ray",
    documentName: "Pelvic X-Ray",
    documentDate: "2024-07-17",
    documentPath: "/documents/9/pelvic_xray.pdf",
    encounterNumber: "E050",
  },
  {
    chartNumber: 9,
    documentType: "Medical Report",
    documentName: "Neurology Evaluation",
    documentDate: "2024-07-19",
    documentPath: "/documents/9/neurology_evaluation.pdf",
    encounterNumber: "E051",
  },
  {
    chartNumber: 9,
    documentType: "Referral",
    documentName: "Oncology Specialist",
    documentDate: "2024-07-21",
    documentPath: "/documents/9/oncology_referral.pdf",
    encounterNumber: "E052",
  },
  {
    chartNumber: 9,
    documentType: "Prescription",
    documentName: "Anti-Inflammatory Medication",
    documentDate: "2024-07-23",
    documentPath: "/documents/9/anti_inflammatory_medication.pdf",
    encounterNumber: "E053",
  },
  {
    chartNumber: 9,
    documentType: "Medical Report",
    documentName: "Cardiac Stress Test",
    documentDate: "2024-07-25",
    documentPath: "/documents/9/cardiac_stress_test.pdf",
    encounterNumber: "E054",
  },
  {
    chartNumber: 10,
    documentType: "X-Ray",
    documentName: "Hip X-Ray",
    documentDate: "2024-07-30",
    documentPath: "/documents/10/hip_xray.pdf",
    encounterNumber: "E055",
  },
  {
    chartNumber: 10,
    documentType: "Medical Report",
    documentName: "Orthopedic Assessment",
    documentDate: "2024-08-01",
    documentPath: "/documents/10/orthopedic_assessment.pdf",
    encounterNumber: "E056",
  },
  {
    chartNumber: 10,
    documentType: "Referral",
    documentName: "Ophthalmology Specialist",
    documentDate: "2024-08-03",
    documentPath: "/documents/10/ophthalmology_referral.pdf",
    encounterNumber: "E057",
  },
  {
    chartNumber: 10,
    documentType: "Prescription",
    documentName: "Eye Drops",
    documentDate: "2024-08-05",
    documentPath: "/documents/10/eye_drops.pdf",
    encounterNumber: "E058",
  },
  {
    chartNumber: 10,
    documentType: "Lab Results",
    documentName: "Basic Metabolic Panel",
    documentDate: "2024-08-07",
    documentPath: "/documents/10/basic_metabolic_panel.pdf",
    encounterNumber: "E059",
  },
  {
    chartNumber: 10,
    documentType: "Medical Report",
    documentName: "Gastroenterology Follow-Up",
    documentDate: "2024-08-09",
    documentPath: "/documents/10/gastroenterology_follow_up.pdf",
    encounterNumber: "E060",
  },
];
