export const documentsData = [
  {
    chartNumber: 1,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 1,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 1,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 2,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 2,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 2,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 3,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 3,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 3,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 4,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 4,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 4,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 5,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 5,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
  {
    chartNumber: 5,
    documentType: "",
    documentName: "",
    documentDate: "",
    documentPath: "",
    encounterNumber: "",
  },
];
