export const documentsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    documentType: "Medical Report",
    documentName: "Blood Test Results",
    documentDate: "2024-08-10",
    documentPath: "/documents/1/blood_test_results.pdf",
    encounterNumber: "ENC001",
  },
  {
    chartNumber: 1,
    documentType: "X-Ray",
    documentName: "Chest X-Ray",
    documentDate: "2024-08-11",
    documentPath: "/documents/1/chest_xray.pdf",
    encounterNumber: "ENC002",
  },
  {
    chartNumber: 1,
    documentType: "Prescription",
    documentName: "Painkillers Prescription",
    documentDate: "2024-08-12",
    documentPath: "/documents/1/painkillers_prescription.pdf",
    encounterNumber: "ENC003",
  },
  {
    chartNumber: 1,
    documentType: "Lab Results",
    documentName: "Blood Test Report",
    documentDate: "2024-05-01",
    documentPath: "/documents/1/blood_test_report.pdf",
    encounterNumber: "ENC016",
  },
  {
    chartNumber: 1,
    documentType: "Prescription",
    documentName: "Antibiotics",
    documentDate: "2024-05-03",
    documentPath: "/documents/1/antibiotics.pdf",
    encounterNumber: "ENC017",
  },
  {
    chartNumber: 1,
    documentType: "Referral",
    documentName: "Orthopedic Specialist",
    documentDate: "2024-05-06",
    documentPath: "/documents/1/orthopedic_referral.pdf",
    encounterNumber: "ENC018",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    documentType: "Medical Report",
    documentName: "Annual Physical Exam",
    documentDate: "2024-07-01",
    documentPath: "/documents/2/annual_physical_exam.pdf",
    encounterNumber: "ENC004",
  },
  {
    chartNumber: 2,
    documentType: "Lab Results",
    documentName: "Urine Test",
    documentDate: "2024-07-05",
    documentPath: "/documents/2/urine_test.pdf",
    encounterNumber: "ENC005",
  },
  {
    chartNumber: 2,
    documentType: "Prescription",
    documentName: "Antibiotics Prescription",
    documentDate: "2024-07-07",
    documentPath: "/documents/2/antibiotics_prescription.pdf",
    encounterNumber: "ENC006",
  },
  {
    chartNumber: 2,
    documentType: "X-Ray",
    documentName: "Chest X-Ray",
    documentDate: "2024-05-10",
    documentPath: "/documents/2/chest_xray.pdf",
    encounterNumber: "ENC019",
  },
  {
    chartNumber: 2,
    documentType: "Medical Report",
    documentName: "Annual Physical Exam",
    documentDate: "2024-05-12",
    documentPath: "/documents/2/annual_physical_report.pdf",
    encounterNumber: "ENC020",
  },
  {
    chartNumber: 2,
    documentType: "Lab Results",
    documentName: "Cholesterol Screening",
    documentDate: "2024-05-14",
    documentPath: "/documents/2/cholesterol_screening.pdf",
    encounterNumber: "ENC021",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    documentType: "Medical Report",
    documentName: "Eye Examination",
    documentDate: "2024-06-15",
    documentPath: "/documents/3/eye_examination.pdf",
    encounterNumber: "ENC007",
  },
  {
    chartNumber: 3,
    documentType: "X-Ray",
    documentName: "Dental X-Ray",
    documentDate: "2024-06-17",
    documentPath: "/documents/3/dental_xray.pdf",
    encounterNumber: "ENC008",
  },
  {
    chartNumber: 3,
    documentType: "Prescription",
    documentName: "Glasses Prescription",
    documentDate: "2024-06-20",
    documentPath: "/documents/3/glasses_prescription.pdf",
    encounterNumber: "ENC009",
  },
  {
    chartNumber: 3,
    documentType: "Medical Report",
    documentName: "Cardiology Consultation",
    documentDate: "2024-05-18",
    documentPath: "/documents/3/cardiology_consultation.pdf",
    encounterNumber: "ENC022",
  },
  {
    chartNumber: 3,
    documentType: "Prescription",
    documentName: "Blood Pressure Medication",
    documentDate: "2024-05-20",
    documentPath: "/documents/3/blood_pressure_medication.pdf",
    encounterNumber: "ENC023",
  },
  {
    chartNumber: 3,
    documentType: "X-Ray",
    documentName: "Spine X-Ray",
    documentDate: "2024-05-22",
    documentPath: "/documents/3/spine_xray.pdf",
    encounterNumber: "ENC024",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    documentType: "Medical Report",
    documentName: "EKG Results",
    documentDate: "2024-05-10",
    documentPath: "/documents/4/ekg_results.pdf",
    encounterNumber: "ENC010",
  },
  {
    chartNumber: 4,
    documentType: "X-Ray",
    documentName: "Abdominal X-Ray",
    documentDate: "2024-05-12",
    documentPath: "/documents/4/abdominal_xray.pdf",
    encounterNumber: "ENC011",
  },
  {
    chartNumber: 4,
    documentType: "Prescription",
    documentName: "Blood Pressure Medication",
    documentDate: "2024-05-15",
    documentPath: "/documents/4/blood_pressure_medication.pdf",
    encounterNumber: "ENC012",
  },
  {
    chartNumber: 4,
    documentType: "Lab Results",
    documentName: "Diabetes Screening",
    documentDate: "2024-05-25",
    documentPath: "/documents/4/diabetes_screening.pdf",
    encounterNumber: "ENC025",
  },
  {
    chartNumber: 4,
    documentType: "Medical Report",
    documentName: "Pulmonary Function Test",
    documentDate: "2024-05-28",
    documentPath: "/documents/4/pulmonary_function_test.pdf",
    encounterNumber: "ENC026",
  },
  {
    chartNumber: 4,
    documentType: "Referral",
    documentName: "Dermatology Specialist",
    documentDate: "2024-05-30",
    documentPath: "/documents/4/dermatology_referral.pdf",
    encounterNumber: "ENC027",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    documentType: "Medical Report",
    documentName: "MRI Results",
    documentDate: "2024-04-25",
    documentPath: "/documents/5/mri_results.pdf",
    encounterNumber: "ENC013",
  },
  {
    chartNumber: 5,
    documentType: "X-Ray",
    documentName: "Hand X-Ray",
    documentDate: "2024-04-27",
    documentPath: "/documents/5/hand_xray.pdf",
    encounterNumber: "ENC014",
  },
  {
    chartNumber: 5,
    documentType: "Prescription",
    documentName: "Vitamin D Supplements",
    documentDate: "2024-04-30",
    documentPath: "/documents/5/vitamin_d_supplements.pdf",
    encounterNumber: "ENC015",
  },
  {
    chartNumber: 5,
    documentType: "Medical Report",
    documentName: "MRI Results",
    documentDate: "2024-04-25",
    documentPath: "/documents/5/mri_results.pdf",
    encounterNumber: "ENC028",
  },
  {
    chartNumber: 5,
    documentType: "X-Ray",
    documentName: "Hand X-Ray",
    documentDate: "2024-04-27",
    documentPath: "/documents/5/hand_xray.pdf",
    encounterNumber: "ENC029",
  },
  {
    chartNumber: 5,
    documentType: "Prescription",
    documentName: "Vitamin D Supplements",
    documentDate: "2024-04-30",
    documentPath: "/documents/5/vitamin_d_supplements.pdf",
    encounterNumber: "ENC030",
  },
  {
    chartNumber: 6,
    documentType: "Lab Results",
    documentName: "Thyroid Panel",
    documentDate: "2024-06-01",
    documentPath: "/documents/6/thyroid_panel.pdf",
    encounterNumber: "ENC031",
  },
  {
    chartNumber: 6,
    documentType: "Medical Report",
    documentName: "Neurology Consultation",
    documentDate: "2024-06-03",
    documentPath: "/documents/6/neurology_consultation.pdf",
    encounterNumber: "ENC032",
  },
  {
    chartNumber: 6,
    documentType: "Prescription",
    documentName: "Cholesterol Medication",
    documentDate: "2024-06-05",
    documentPath: "/documents/6/cholesterol_medication.pdf",
    encounterNumber: "ENC033",
  },
  {
    chartNumber: 6,
    documentType: "X-Ray",
    documentName: "Knee X-Ray",
    documentDate: "2024-06-07",
    documentPath: "/documents/6/knee_xray.pdf",
    encounterNumber: "ENC034",
  },
  {
    chartNumber: 6,
    documentType: "Referral",
    documentName: "Gastroenterology Specialist",
    documentDate: "2024-06-09",
    documentPath: "/documents/6/gastroenterology_referral.pdf",
    encounterNumber: "ENC035",
  },
  {
    chartNumber: 6,
    documentType: "Medical Report",
    documentName: "Physical Therapy Plan",
    documentDate: "2024-06-11",
    documentPath: "/documents/6/physical_therapy_plan.pdf",
    encounterNumber: "ENC036",
  },
  {
    chartNumber: 7,
    documentType: "Prescription",
    documentName: "Allergy Medication",
    documentDate: "2024-06-15",
    documentPath: "/documents/7/allergy_medication.pdf",
    encounterNumber: "ENC037",
  },
  {
    chartNumber: 7,
    documentType: "Lab Results",
    documentName: "Complete Blood Count",
    documentDate: "2024-06-17",
    documentPath: "/documents/7/complete_blood_count.pdf",
    encounterNumber: "ENC038",
  },
  {
    chartNumber: 7,
    documentType: "X-Ray",
    documentName: "Shoulder X-Ray",
    documentDate: "2024-06-19",
    documentPath: "/documents/7/shoulder_xray.pdf",
    encounterNumber: "ENC039",
  },
  {
    chartNumber: 7,
    documentType: "Medical Report",
    documentName: "Annual Wellness Check",
    documentDate: "2024-06-21",
    documentPath: "/documents/7/annual_wellness_check.pdf",
    encounterNumber: "ENC040",
  },
  {
    chartNumber: 7,
    documentType: "Referral",
    documentName: "Cardiology Specialist",
    documentDate: "2024-06-23",
    documentPath: "/documents/7/cardiology_referral.pdf",
    encounterNumber: "ENC041",
  },
  {
    chartNumber: 7,
    documentType: "Prescription",
    documentName: "Pain Reliever",
    documentDate: "2024-06-25",
    documentPath: "/documents/7/pain_reliever.pdf",
    encounterNumber: "ENC042",
  },
  {
    chartNumber: 8,
    documentType: "Medical Report",
    documentName: "Dermatology Follow-Up",
    documentDate: "2024-07-01",
    documentPath: "/documents/8/dermatology_follow_up.pdf",
    encounterNumber: "ENC043",
  },
  {
    chartNumber: 8,
    documentType: "Lab Results",
    documentName: "Lipid Profile",
    documentDate: "2024-07-03",
    documentPath: "/documents/8/lipid_profile.pdf",
    encounterNumber: "ENC044",
  },
  {
    chartNumber: 8,
    documentType: "X-Ray",
    documentName: "Ankle X-Ray",
    documentDate: "2024-07-05",
    documentPath: "/documents/8/ankle_xray.pdf",
    encounterNumber: "ENC045",
  },
  {
    chartNumber: 8,
    documentType: "Referral",
    documentName: "Endocrinology Specialist",
    documentDate: "2024-07-07",
    documentPath: "/documents/8/endocrinology_referral.pdf",
    encounterNumber: "ENC046",
  },
  {
    chartNumber: 8,
    documentType: "Prescription",
    documentName: "Diabetes Medication",
    documentDate: "2024-07-09",
    documentPath: "/documents/8/diabetes_medication.pdf",
    encounterNumber: "ENC047",
  },
  {
    chartNumber: 8,
    documentType: "Medical Report",
    documentName: "Surgery Follow-Up",
    documentDate: "2024-07-11",
    documentPath: "/documents/8/surgery_follow_up.pdf",
    encounterNumber: "ENC048",
  },
  {
    chartNumber: 9,
    documentType: "Lab Results",
    documentName: "Renal Function Panel",
    documentDate: "2024-07-15",
    documentPath: "/documents/9/renal_function_panel.pdf",
    encounterNumber: "ENC049",
  },
  {
    chartNumber: 9,
    documentType: "X-Ray",
    documentName: "Pelvic X-Ray",
    documentDate: "2024-07-17",
    documentPath: "/documents/9/pelvic_xray.pdf",
    encounterNumber: "ENC050",
  },
  {
    chartNumber: 9,
    documentType: "Medical Report",
    documentName: "Neurology Evaluation",
    documentDate: "2024-07-19",
    documentPath: "/documents/9/neurology_evaluation.pdf",
    encounterNumber: "ENC051",
  },
  {
    chartNumber: 9,
    documentType: "Referral",
    documentName: "Oncology Specialist",
    documentDate: "2024-07-21",
    documentPath: "/documents/9/oncology_referral.pdf",
    encounterNumber: "ENC052",
  },
  {
    chartNumber: 9,
    documentType: "Prescription",
    documentName: "Anti-Inflammatory Medication",
    documentDate: "2024-07-23",
    documentPath: "/documents/9/anti_inflammatory_medication.pdf",
    encounterNumber: "ENC053",
  },
  {
    chartNumber: 9,
    documentType: "Medical Report",
    documentName: "Cardiac Stress Test",
    documentDate: "2024-07-25",
    documentPath: "/documents/9/cardiac_stress_test.pdf",
    encounterNumber: "ENC054",
  },
  {
    chartNumber: 10,
    documentType: "X-Ray",
    documentName: "Hip X-Ray",
    documentDate: "2024-07-30",
    documentPath: "/documents/10/hip_xray.pdf",
    encounterNumber: "ENC055",
  },
  {
    chartNumber: 10,
    documentType: "Medical Report",
    documentName: "Orthopedic Assessment",
    documentDate: "2024-08-01",
    documentPath: "/documents/10/orthopedic_assessment.pdf",
    encounterNumber: "ENC056",
  },
  {
    chartNumber: 10,
    documentType: "Referral",
    documentName: "Ophthalmology Specialist",
    documentDate: "2024-08-03",
    documentPath: "/documents/10/ophthalmology_referral.pdf",
    encounterNumber: "ENC057",
  },
  {
    chartNumber: 10,
    documentType: "Prescription",
    documentName: "Eye Drops",
    documentDate: "2024-08-05",
    documentPath: "/documents/10/eye_drops.pdf",
    encounterNumber: "ENC058",
  },
  {
    chartNumber: 10,
    documentType: "Lab Results",
    documentName: "Basic Metabolic Panel",
    documentDate: "2024-08-07",
    documentPath: "/documents/10/basic_metabolic_panel.pdf",
    encounterNumber: "ENC059",
  },
  {
    chartNumber: 10,
    documentType: "Medical Report",
    documentName: "Gastroenterology Follow-Up",
    documentDate: "2024-08-09",
    documentPath: "/documents/10/gastroenterology_follow_up.pdf",
    encounterNumber: "ENC060",
  },
];
