export const historyData = [
  // Chart Number 1
  {
    chartNumber: 1,
    historyCategory: "Medical History",
    date: "2024-08-01",
    item: "Annual Checkup",
    description: "Routine physical examination",
    drFirstName: "James",
    drLastName: "Smith",
    results: "All vitals normal",
    notes: "Patient in good health",
    encounterNumber: "ENC001",
  },
  {
    chartNumber: 1,
    historyCategory: "Immunization",
    date: "2024-08-05",
    item: "Flu Vaccine",
    description: "Annual flu vaccination",
    drFirstName: "Laura",
    drLastName: "Johnson",
    results: "Vaccine administered successfully",
    notes: "No side effects reported",
    encounterNumber: "ENC002",
  },
  {
    chartNumber: 1,
    historyCategory: "Lab Results",
    date: "2024-08-10",
    item: "Blood Test",
    description: "Routine blood work",
    drFirstName: "John",
    drLastName: "Doe",
    results: "Cholesterol slightly elevated",
    notes: "Recommend dietary changes",
    encounterNumber: "ENC003",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    historyCategory: "Surgical History",
    date: "2024-07-15",
    item: "Appendectomy",
    description: "Surgical removal of the appendix",
    drFirstName: "Michael",
    drLastName: "Brown",
    results: "Surgery successful",
    notes: "Patient recovering well",
    encounterNumber: "ENC004",
  },
  {
    chartNumber: 2,
    historyCategory: "Medical History",
    date: "2024-07-20",
    item: "Allergy Test",
    description: "Testing for common allergens",
    drFirstName: "Susan",
    drLastName: "Taylor",
    results: "Positive for pollen allergy",
    notes: "Prescribed antihistamines",
    encounterNumber: "ENC005",
  },
  {
    chartNumber: 2,
    historyCategory: "Lab Results",
    date: "2024-07-25",
    item: "Urine Test",
    description: "Routine urine analysis",
    drFirstName: "William",
    drLastName: "Garcia",
    results: "No abnormalities detected",
    notes: "Patient advised to maintain hydration",
    encounterNumber: "ENC006",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    historyCategory: "Immunization",
    date: "2024-06-10",
    item: "Tetanus Shot",
    description: "Tetanus booster vaccine",
    drFirstName: "Sarah",
    drLastName: "Martinez",
    results: "Vaccine administered successfully",
    notes: "Next booster due in 10 years",
    encounterNumber: "ENC007",
  },
  {
    chartNumber: 3,
    historyCategory: "Medical History",
    date: "2024-06-15",
    item: "Vision Test",
    description: "Routine eye examination",
    drFirstName: "Robert",
    drLastName: "Davis",
    results: "Mild myopia detected",
    notes: "Prescription for corrective lenses provided",
    encounterNumber: "ENC008",
  },
  {
    chartNumber: 3,
    historyCategory: "Surgical History",
    date: "2024-06-20",
    item: "Tonsillectomy",
    description: "Surgical removal of tonsils",
    drFirstName: "Karen",
    drLastName: "Lee",
    results: "Surgery successful",
    notes: "Patient advised on post-op care",
    encounterNumber: "ENC009",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    historyCategory: "Medical History",
    date: "2024-05-05",
    item: "Cardiac Stress Test",
    description: "Testing heart function under stress",
    drFirstName: "Brian",
    drLastName: "White",
    results: "No abnormalities detected",
    notes: "Patient advised to maintain regular exercise",
    encounterNumber: "ENC010",
  },
  {
    chartNumber: 4,
    historyCategory: "Lab Results",
    date: "2024-05-10",
    item: "Blood Sugar Test",
    description: "Routine glucose level check",
    drFirstName: "Nancy",
    drLastName: "Harris",
    results: "Blood sugar levels within normal range",
    notes: "No further action required",
    encounterNumber: "ENC011",
  },
  {
    chartNumber: 4,
    historyCategory: "Surgical History",
    date: "2024-05-15",
    item: "Knee Arthroscopy",
    description: "Minimally invasive knee surgery",
    drFirstName: "Jason",
    drLastName: "Clark",
    results: "Surgery successful, minor scarring",
    notes: "Patient advised on rehabilitation exercises",
    encounterNumber: "ENC012",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    historyCategory: "Immunization",
    date: "2024-04-01",
    item: "Hepatitis B Vaccine",
    description: "First dose of Hepatitis B vaccine",
    drFirstName: "Deborah",
    drLastName: "Walker",
    results: "Vaccine administered successfully",
    notes: "Second dose scheduled in one month",
    encounterNumber: "ENC013",
  },
  {
    chartNumber: 5,
    historyCategory: "Medical History",
    date: "2024-04-10",
    item: "Hearing Test",
    description: "Routine hearing examination",
    drFirstName: "Frank",
    drLastName: "Allen",
    results: "Hearing within normal range",
    notes: "No further action required",
    encounterNumber: "ENC014",
  },
  {
    chartNumber: 5,
    historyCategory: "Lab Results",
    date: "2024-04-15",
    item: "Liver Function Test",
    description: "Routine check of liver enzymes",
    drFirstName: "Jessica",
    drLastName: "King",
    results: "Liver function normal",
    notes: "Patient advised to avoid excessive alcohol consumption",
    encounterNumber: "ENC015",
  },
];
