export const historyData = [
  // Chart Number 1
  {
    chartNumber: 1,
    historyCategory: "Medical History",
    date: "2024-08-01",
    item: "Annual Checkup",
    description: "Routine physical examination",
    drFirstName: "James",
    drLastName: "Smith",
    results: "All vitals normal",
    notes: "Patient in good health",
    encounterNumber: "E001",
  },
  {
    chartNumber: 1,
    historyCategory: "Immunization",
    date: "2024-08-05",
    item: "Flu Vaccine",
    description: "Annual flu vaccination",
    drFirstName: "Laura",
    drLastName: "Johnson",
    results: "Vaccine administered successfully",
    notes: "No side effects reported",
    encounterNumber: "E002",
  },
  {
    chartNumber: 1,
    historyCategory: "Lab Results",
    date: "2024-08-10",
    item: "Blood Test",
    description: "Routine blood work",
    drFirstName: "John",
    drLastName: "Doe",
    results: "Cholesterol slightly elevated",
    notes: "Recommend dietary changes",
    encounterNumber: "E003",
  },
  {
    chartNumber: 1,
    historyCategory: "Medical History",
    date: "2024-08-12",
    item: "Cardiology Consultation",
    description: "Evaluation for heart palpitations",
    drFirstName: "Michael",
    drLastName: "Brown",
    results: "No significant findings",
    notes: "No further action required",
    encounterNumber: "E004",
  },
  {
    chartNumber: 1,
    historyCategory: "Lab Results",
    date: "2024-08-15",
    item: "Glucose Test",
    description: "Fasting blood glucose test",
    drFirstName: "Anna",
    drLastName: "Taylor",
    results: "Normal glucose levels",
    notes: "No signs of diabetes",
    encounterNumber: "E005",
  },
  {
    chartNumber: 1,
    historyCategory: "Immunization",
    date: "2024-08-18",
    item: "Hepatitis B Vaccine",
    description: "First dose of Hepatitis B vaccine",
    drFirstName: "Sarah",
    drLastName: "Wilson",
    results: "Vaccine administered without issues",
    notes: "Schedule for second dose in one month",
    encounterNumber: "E006",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    historyCategory: "Surgical History",
    date: "2024-07-15",
    item: "Appendectomy",
    description: "Surgical removal of the appendix",
    drFirstName: "Michael",
    drLastName: "Brown",
    results: "Surgery successful",
    notes: "Patient recovering well",
    encounterNumber: "E007",
  },
  {
    chartNumber: 2,
    historyCategory: "Medical History",
    date: "2024-07-20",
    item: "Allergy Test",
    description: "Testing for common allergens",
    drFirstName: "Susan",
    drLastName: "Taylor",
    results: "Positive for pollen allergy",
    notes: "Prescribed antihistamines",
    encounterNumber: "E008",
  },
  {
    chartNumber: 2,
    historyCategory: "Lab Results",
    date: "2024-07-25",
    item: "Urine Test",
    description: "Routine urine analysis",
    drFirstName: "William",
    drLastName: "Garcia",
    results: "No abnormalities detected",
    notes: "Patient advised to maintain hydration",
    encounterNumber: "E009",
  },
  {
    chartNumber: 2,
    historyCategory: "Medical History",
    date: "2024-08-20",
    item: "Dermatology Consultation",
    description: "Evaluation of skin rash",
    drFirstName: "Robert",
    drLastName: "Martinez",
    results: "Rash diagnosed as eczema",
    notes: "Prescribed topical corticosteroids",
    encounterNumber: "E010",
  },
  {
    chartNumber: 2,
    historyCategory: "Lab Results",
    date: "2024-08-22",
    item: "Lipid Panel",
    description: "Cholesterol and triglyceride levels",
    drFirstName: "Emily",
    drLastName: "Garcia",
    results: "Elevated LDL cholesterol",
    notes: "Recommend dietary changes and follow-up",
    encounterNumber: "E011",
  },
  {
    chartNumber: 2,
    historyCategory: "Immunization",
    date: "2024-08-25",
    item: "Tetanus Booster",
    description: "10-year tetanus booster shot",
    drFirstName: "Christopher",
    drLastName: "Clark",
    results: "Booster administered successfully",
    notes: "Next booster due in 10 years",
    encounterNumber: "E012",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    historyCategory: "Immunization",
    date: "2024-06-10",
    item: "Tetanus Shot",
    description: "Tetanus booster vaccine",
    drFirstName: "Sarah",
    drLastName: "Martinez",
    results: "Vaccine administered successfully",
    notes: "Next booster due in 10 years",
    encounterNumber: "E013",
  },
  {
    chartNumber: 3,
    historyCategory: "Medical History",
    date: "2024-06-15",
    item: "Vision Test",
    description: "Routine eye examination",
    drFirstName: "Robert",
    drLastName: "Davis",
    results: "Mild myopia detected",
    notes: "Prescription for corrective lenses provided",
    encounterNumber: "E014",
  },
  {
    chartNumber: 3,
    historyCategory: "Surgical History",
    date: "2024-06-20",
    item: "Tonsillectomy",
    description: "Surgical removal of tonsils",
    drFirstName: "Karen",
    drLastName: "Lee",
    results: "Surgery successful",
    notes: "Patient advised on post-op care",
    encounterNumber: "E015",
  },
  {
    chartNumber: 3,
    historyCategory: "Medical History",
    date: "2024-08-28",
    item: "ENT Consultation",
    description: "Evaluation of chronic sinusitis",
    drFirstName: "David",
    drLastName: "Lewis",
    results: "Diagnosis of chronic sinusitis",
    notes: "Prescribed nasal corticosteroids",
    encounterNumber: "E016",
  },
  {
    chartNumber: 3,
    historyCategory: "Lab Results",
    date: "2024-09-01",
    item: "Complete Blood Count",
    description: "Routine blood test",
    drFirstName: "Susan",
    drLastName: "Walker",
    results: "All parameters within normal range",
    notes: "No further action needed",
    encounterNumber: "E017",
  },
  {
    chartNumber: 3,
    historyCategory: "Immunization",
    date: "2024-09-05",
    item: "Pneumococcal Vaccine",
    description: "Vaccination against pneumococcal disease",
    drFirstName: "Daniel",
    drLastName: "Harris",
    results: "Vaccine administered successfully",
    notes: "No adverse reactions",
    encounterNumber: "E018",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    historyCategory: "Medical History",
    date: "2024-05-05",
    item: "Cardiac Stress Test",
    description: "Testing heart function under stress",
    drFirstName: "Brian",
    drLastName: "White",
    results: "No abnormalities detected",
    notes: "Patient advised to maintain regular exercise",
    encounterNumber: "E019",
  },
  {
    chartNumber: 4,
    historyCategory: "Lab Results",
    date: "2024-05-10",
    item: "Blood Sugar Test",
    description: "Routine glucose level check",
    drFirstName: "Nancy",
    drLastName: "Harris",
    results: "Blood sugar levels within normal range",
    notes: "No further action required",
    encounterNumber: "E020",
  },
  {
    chartNumber: 4,
    historyCategory: "Surgical History",
    date: "2024-05-15",
    item: "Knee Arthroscopy",
    description: "Minimally invasive knee surgery",
    drFirstName: "Jason",
    drLastName: "Clark",
    results: "Surgery successful, minor scarring",
    notes: "Patient advised on rehabilitation exercises",
    encounterNumber: "E021",
  },
  {
    chartNumber: 4,
    historyCategory: "Medical History",
    date: "2024-09-10",
    item: "Orthopedic Consultation",
    description: "Evaluation of knee pain",
    drFirstName: "Patricia",
    drLastName: "Hall",
    results: "Diagnosis of mild osteoarthritis",
    notes: "Recommend physical therapy",
    encounterNumber: "E022",
  },
  {
    chartNumber: 4,
    historyCategory: "Lab Results",
    date: "2024-09-15",
    item: "Liver Function Test",
    description: "Routine liver enzyme check",
    drFirstName: "Matthew",
    drLastName: "Young",
    results: "Elevated ALT levels",
    notes: "Recommend further testing",
    encounterNumber: "E023",
  },
  {
    chartNumber: 4,
    historyCategory: "Immunization",
    date: "2024-09-20",
    item: "MMR Vaccine",
    description: "Second dose of MMR vaccine",
    drFirstName: "Barbara",
    drLastName: "King",
    results: "Vaccine administered without issues",
    notes: "No adverse reactions",
    encounterNumber: "E024",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    historyCategory: "Immunization",
    date: "2024-04-01",
    item: "Hepatitis B Vaccine",
    description: "First dose of Hepatitis B vaccine",
    drFirstName: "Deborah",
    drLastName: "Walker",
    results: "Vaccine administered successfully",
    notes: "Second dose scheduled in one month",
    encounterNumber: "E025",
  },
  {
    chartNumber: 5,
    historyCategory: "Medical History",
    date: "2024-04-10",
    item: "Hearing Test",
    description: "Routine hearing examination",
    drFirstName: "Frank",
    drLastName: "Allen",
    results: "Hearing within normal range",
    notes: "No further action required",
    encounterNumber: "E026",
  },
  {
    chartNumber: 5,
    historyCategory: "Lab Results",
    date: "2024-04-15",
    item: "Liver Function Test",
    description: "Routine check of liver enzymes",
    drFirstName: "Jessica",
    drLastName: "King",
    results: "Liver function normal",
    notes: "Patient advised to avoid excessive alcohol consumption",
    encounterNumber: "E027",
  },
  {
    chartNumber: 5,
    historyCategory: "Medical History",
    date: "2024-09-25",
    item: "Gastroenterology Consultation",
    description: "Evaluation of abdominal pain",
    drFirstName: "Joseph",
    drLastName: "Wright",
    results: "Diagnosis of IBS",
    notes: "Recommend dietary changes and medication",
    encounterNumber: "E028",
  },
  {
    chartNumber: 5,
    historyCategory: "Lab Results",
    date: "2024-09-30",
    item: "Kidney Function Test",
    description: "Routine kidney enzyme check",
    drFirstName: "Linda",
    drLastName: "Lopez",
    results: "Normal kidney function",
    notes: "No further action needed",
    encounterNumber: "E029",
  },
  {
    chartNumber: 5,
    historyCategory: "Immunization",
    date: "2024-10-05",
    item: "COVID-19 Booster",
    description: "Third dose of COVID-19 vaccine",
    drFirstName: "Kevin",
    drLastName: "Hill",
    results: "Booster administered successfully",
    notes: "No side effects reported",
    encounterNumber: "E030",
  },
  {
    chartNumber: 6,
    historyCategory: "Medical History",
    date: "2024-08-01",
    item: "Neurology Consultation",
    description: "Evaluation of chronic headaches",
    drFirstName: "Margaret",
    drLastName: "Anderson",
    results: "Migraines diagnosed",
    notes: "Prescribed medication for management",
    encounterNumber: "E031",
  },
  {
    chartNumber: 6,
    historyCategory: "Lab Results",
    date: "2024-08-03",
    item: "Thyroid Function Test",
    description: "Routine thyroid check",
    drFirstName: "William",
    drLastName: "Lee",
    results: "Normal thyroid levels",
    notes: "No further action required",
    encounterNumber: "E032",
  },
  {
    chartNumber: 6,
    historyCategory: "Immunization",
    date: "2024-08-05",
    item: "HPV Vaccine",
    description: "Second dose of HPV vaccine",
    drFirstName: "Emily",
    drLastName: "Clark",
    results: "Vaccine administered without issues",
    notes: "No adverse reactions reported",
    encounterNumber: "E033",
  },
  {
    chartNumber: 6,
    historyCategory: "Medical History",
    date: "2024-08-07",
    item: "Dermatology Consultation",
    description: "Evaluation of mole growth",
    drFirstName: "Jessica",
    drLastName: "Walker",
    results: "Mole removed and sent for biopsy",
    notes: "Awaiting biopsy results",
    encounterNumber: "E034",
  },
  {
    chartNumber: 6,
    historyCategory: "Lab Results",
    date: "2024-08-10",
    item: "Complete Blood Count",
    description: "Routine blood test",
    drFirstName: "Michael",
    drLastName: "Harris",
    results: "All parameters normal",
    notes: "No further action required",
    encounterNumber: "E035",
  },
  {
    chartNumber: 6,
    historyCategory: "Immunization",
    date: "2024-08-12",
    item: "Tetanus Booster",
    description: "10-year tetanus booster",
    drFirstName: "Linda",
    drLastName: "Martinez",
    results: "Booster administered successfully",
    notes: "Next booster due in 10 years",
    encounterNumber: "E036",
  },
  {
    chartNumber: 7,
    historyCategory: "Medical History",
    date: "2024-08-15",
    item: "Ophthalmology Consultation",
    description: "Evaluation of blurred vision",
    drFirstName: "David",
    drLastName: "Young",
    results: "Prescription glasses recommended",
    notes: "No signs of serious eye conditions",
    encounterNumber: "E037",
  },
  {
    chartNumber: 7,
    historyCategory: "Lab Results",
    date: "2024-08-18",
    item: "Liver Function Test",
    description: "Routine liver enzyme check",
    drFirstName: "Susan",
    drLastName: "Robinson",
    results: "Elevated ALT levels",
    notes: "Recommend follow-up with hepatologist",
    encounterNumber: "E038",
  },
  {
    chartNumber: 7,
    historyCategory: "Immunization",
    date: "2024-08-21",
    item: "Shingles Vaccine",
    description: "First dose of shingles vaccine",
    drFirstName: "Daniel",
    drLastName: "Perez",
    results: "Vaccine administered without issues",
    notes: "Second dose scheduled in 2 months",
    encounterNumber: "E039",
  },
  {
    chartNumber: 7,
    historyCategory: "Medical History",
    date: "2024-08-25",
    item: "Pulmonology Consultation",
    description: "Evaluation of chronic cough",
    drFirstName: "Karen",
    drLastName: "Lewis",
    results: "Mild asthma diagnosed",
    notes: "Inhaler prescribed",
    encounterNumber: "E040",
  },
  {
    chartNumber: 7,
    historyCategory: "Lab Results",
    date: "2024-08-28",
    item: "Urinalysis",
    description: "Routine urine test",
    drFirstName: "Robert",
    drLastName: "King",
    results: "No signs of infection",
    notes: "Patient advised to maintain hydration",
    encounterNumber: "E041",
  },
  {
    chartNumber: 7,
    historyCategory: "Immunization",
    date: "2024-08-30",
    item: "Hepatitis A Vaccine",
    description: "First dose of Hepatitis A vaccine",
    drFirstName: "Patricia",
    drLastName: "Scott",
    results: "Vaccine administered successfully",
    notes: "Schedule for second dose in 6 months",
    encounterNumber: "E042",
  },
  {
    chartNumber: 8,
    historyCategory: "Medical History",
    date: "2024-09-01",
    item: "Gastroenterology Consultation",
    description: "Evaluation of chronic heartburn",
    drFirstName: "John",
    drLastName: "Taylor",
    results: "GERD diagnosed",
    notes: "Medication prescribed",
    encounterNumber: "E043",
  },
  {
    chartNumber: 8,
    historyCategory: "Lab Results",
    date: "2024-09-04",
    item: "Cholesterol Test",
    description: "Routine cholesterol check",
    drFirstName: "Sarah",
    drLastName: "White",
    results: "Elevated cholesterol levels",
    notes: "Recommend dietary changes",
    encounterNumber: "E044",
  },
  {
    chartNumber: 8,
    historyCategory: "Immunization",
    date: "2024-09-07",
    item: "Influenza Vaccine",
    description: "Annual flu shot",
    drFirstName: "Charles",
    drLastName: "Thompson",
    results: "Vaccine administered successfully",
    notes: "No adverse reactions reported",
    encounterNumber: "E045",
  },
  {
    chartNumber: 8,
    historyCategory: "Medical History",
    date: "2024-09-10",
    item: "Neurology Consultation",
    description: "Evaluation of numbness in extremities",
    drFirstName: "Jennifer",
    drLastName: "Lopez",
    results: "Peripheral neuropathy diagnosed",
    notes: "Further testing recommended",
    encounterNumber: "E046",
  },
  {
    chartNumber: 8,
    historyCategory: "Lab Results",
    date: "2024-09-13",
    item: "Blood Glucose Test",
    description: "Routine blood sugar check",
    drFirstName: "Christopher",
    drLastName: "Brown",
    results: "Normal glucose levels",
    notes: "No signs of diabetes",
    encounterNumber: "E047",
  },
  {
    chartNumber: 8,
    historyCategory: "Immunization",
    date: "2024-09-16",
    item: "Pneumonia Vaccine",
    description: "First dose of pneumonia vaccine",
    drFirstName: "Maria",
    drLastName: "Davis",
    results: "Vaccine administered without issues",
    notes: "No adverse reactions",
    encounterNumber: "E048",
  },
  {
    chartNumber: 9,
    historyCategory: "Medical History",
    date: "2024-09-18",
    item: "Rheumatology Consultation",
    description: "Evaluation of joint pain",
    drFirstName: "Kevin",
    drLastName: "Rodriguez",
    results: "Rheumatoid arthritis diagnosed",
    notes: "Medication and physical therapy recommended",
    encounterNumber: "E049",
  },
  {
    chartNumber: 9,
    historyCategory: "Lab Results",
    date: "2024-09-21",
    item: "Kidney Function Test",
    description: "Routine kidney enzyme check",
    drFirstName: "Laura",
    drLastName: "Garcia",
    results: "Normal kidney function",
    notes: "No further action required",
    encounterNumber: "E050",
  },
  {
    chartNumber: 9,
    historyCategory: "Immunization",
    date: "2024-09-24",
    item: "Tetanus Booster",
    description: "10-year tetanus booster",
    drFirstName: "Mark",
    drLastName: "Martinez",
    results: "Booster administered successfully",
    notes: "Next booster due in 10 years",
    encounterNumber: "E051",
  },
  {
    chartNumber: 9,
    historyCategory: "Medical History",
    date: "2024-09-27",
    item: "Endocrinology Consultation",
    description: "Evaluation of thyroid nodule",
    drFirstName: "Angela",
    drLastName: "Hernandez",
    results: "Nodule benign, no treatment needed",
    notes: "Recommend annual follow-up",
    encounterNumber: "E052",
  },
  {
    chartNumber: 9,
    historyCategory: "Lab Results",
    date: "2024-09-30",
    item: "Vitamin D Test",
    description: "Routine Vitamin D check",
    drFirstName: "Brian",
    drLastName: "Wilson",
    results: "Low Vitamin D levels",
    notes: "Vitamin D supplement recommended",
    encounterNumber: "E053",
  },
  {
    chartNumber: 9,
    historyCategory: "Immunization",
    date: "2024-10-02",
    item: "MMR Vaccine",
    description: "First dose of MMR vaccine",
    drFirstName: "Nancy",
    drLastName: "Clark",
    results: "Vaccine administered successfully",
    notes: "No adverse reactions",
    encounterNumber: "E054",
  },
  {
    chartNumber: 10,
    historyCategory: "Medical History",
    date: "2024-10-05",
    item: "Orthopedics Consultation",
    description: "Evaluation of knee pain",
    drFirstName: "Eric",
    drLastName: "Lewis",
    results: "Mild osteoarthritis diagnosed",
    notes: "Physical therapy recommended",
    encounterNumber: "E055",
  },
  {
    chartNumber: 10,
    historyCategory: "Lab Results",
    date: "2024-10-08",
    item: "Hemoglobin A1c Test",
    description: "Routine diabetes monitoring",
    drFirstName: "Karen",
    drLastName: "Walker",
    results: "A1c within normal range",
    notes: "Continue current management",
    encounterNumber: "E056",
  },
  {
    chartNumber: 10,
    historyCategory: "Immunization",
    date: "2024-10-11",
    item: "DTP Vaccine",
    description: "First dose of DTP vaccine",
    drFirstName: "Michelle",
    drLastName: "Hill",
    results: "Vaccine administered successfully",
    notes: "No adverse reactions",
    encounterNumber: "E057",
  },
  {
    chartNumber: 10,
    historyCategory: "Medical History",
    date: "2024-10-14",
    item: "Cardiology Consultation",
    description: "Evaluation of chest pain",
    drFirstName: "Edward",
    drLastName: "Adams",
    results: "No signs of heart disease",
    notes: "Chest pain likely musculoskeletal",
    encounterNumber: "E058",
  },
  {
    chartNumber: 10,
    historyCategory: "Lab Results",
    date: "2024-10-17",
    item: "Lipid Panel",
    description: "Routine cholesterol check",
    drFirstName: "Barbara",
    drLastName: "Sanchez",
    results: "Elevated LDL levels",
    notes: "Dietary changes recommended",
    encounterNumber: "E059",
  },
  {
    chartNumber: 10,
    historyCategory: "Immunization",
    date: "2024-10-20",
    item: "Hepatitis B Vaccine",
    description: "First dose of Hepatitis B vaccine",
    drFirstName: "Jessica",
    drLastName: "Collins",
    results: "Vaccine administered without issues",
    notes: "Schedule for second dose in 1 month",
    encounterNumber: "E060",
  },
];
