export const labsData = [
  {
    chartNumber: 1,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 1,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 1,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 2,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 2,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 2,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 3,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 3,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 3,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 4,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 4,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 4,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 5,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 5,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
  {
    chartNumber: 5,
    encounterNumber: "",
    labName: "",
    testName: "",
    testDate: "",
    result1: "",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "",
  },
];
