export const labsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    encounterNumber: "E001",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-08-01",
    result1: "WBC: 6.1",
    result2: "RBC: 4.7",
    result3: "Hemoglobin: 13.5",
    result4: "Hematocrit: 40.2",
    result5: "Platelets: 220",
    result6: "MCV: 85",
    result7: "MCH: 29",
    result8: "MCHC: 34",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 1,
    encounterNumber: "E002",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-08-03",
    result1: "Total Cholesterol: 190",
    result2: "HDL: 55",
    result3: "LDL: 120",
    result4: "Triglycerides: 130",
    result5: "VLDL: 15",
    result6: "Non-HDL: 135",
    result7: "Chol/HDL Ratio: 3.5",
    result8: "Glucose: 90",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 1,
    encounterNumber: "E003",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-05",
    result1: "Sodium: 140",
    result2: "Potassium: 4.2",
    result3: "Chloride: 102",
    result4: "CO2: 24",
    result5: "BUN: 18",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 92",
    result8: "Calcium: 9.5",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 1,
    encounterNumber: "E004",
    labName: "LabCorp",
    testName: "Thyroid Function Test",
    testDate: "2024-09-10",
    result1: "TSH: 2.5",
    result2: "Free T4: 1.1",
    result3: "Free T3: 3.0",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-09-11",
  },
  {
    chartNumber: 1,
    encounterNumber: "E005",
    labName: "Quest Diagnostics",
    testName: "Vitamin D Test",
    testDate: "2024-09-15",
    result1: "Vitamin D: 30",
    result2: "Calcium: 9.2",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-09-16",
  },
  {
    chartNumber: 1,
    encounterNumber: "E006",
    labName: "LabCorp",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-09-20",
    result1: "Sodium: 138",
    result2: "Potassium: 4.0",
    result3: "Chloride: 100",
    result4: "CO2: 25",
    result5: "BUN: 17",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 94",
    result8: "Calcium: 9.4",
    resultDate: "2024-09-21",
  },
  {
    chartNumber: 1,
    encounterNumber: "E061",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-08-01",
    result1: "Glucose: 92 mg/dL",
    result2: "Calcium: 9.2 mg/dL",
    result3: "Sodium: 139 mmol/L",
    result4: "Potassium: 4.1 mmol/L",
    result5: "Chloride: 104 mmol/L",
    result6: "CO2: 24 mmol/L",
    result7: "BUN: 14 mg/dL",
    result8: "Creatinine: 1.0 mg/dL",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 1,
    encounterNumber: "E062",
    labName: "LabCorp",
    testName: "Lipid Panel",
    testDate: "2024-08-03",
    result1: "Total Cholesterol: 190 mg/dL",
    result2: "HDL Cholesterol: 55 mg/dL",
    result3: "LDL Cholesterol: 120 mg/dL",
    result4: "Triglycerides: 140 mg/dL",
    result5: "Chol/HDL Ratio: 3.5",
    result6: "Non-HDL Cholesterol: 135 mg/dL",
    result7: "VLDL Cholesterol: 30 mg/dL",
    result8: "Apolipoprotein B: 85 mg/dL",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 1,
    encounterNumber: "E063",
    labName: "BioReference Labs",
    testName: "Thyroid Function Test",
    testDate: "2024-08-05",
    result1: "TSH: 2.1 µIU/mL",
    result2: "Free T4: 1.2 ng/dL",
    result3: "Free T3: 3.4 pg/mL",
    result4: "Total T4: 8.5 µg/dL",
    result5: "Total T3: 140 ng/dL",
    result6: "Thyroid Peroxidase Antibodies: <10 IU/mL",
    result7: "Thyroglobulin Antibodies: 20 IU/mL",
    result8: "Reverse T3: 16 ng/dL",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 1,
    encounterNumber: "E064",
    labName: "Mayo Clinic Laboratories",
    testName: "Urinalysis",
    testDate: "2024-08-07",
    result1: "Color: Yellow",
    result2: "Clarity: Clear",
    result3: "Specific Gravity: 1.015",
    result4: "pH: 6.0",
    result5: "Protein: Trace",
    result6: "Glucose: Negative",
    result7: "Ketones: Negative",
    result8: "Leukocytes: Negative",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 1,
    encounterNumber: "E065",
    labName: "Cedars-Sinai Medical Center",
    testName: "Hematology Panel",
    testDate: "2024-08-09",
    result1: "WBC: 5.6 x10^3/µL",
    result2: "RBC: 4.8 x10^6/µL",
    result3: "Hemoglobin: 14.0 g/dL",
    result4: "Hematocrit: 43.0%",
    result5: "Platelets: 235 x10^3/µL",
    result6: "MCV: 90.0 fL",
    result7: "MCH: 30.0 pg",
    result8: "MCHC: 33.3 g/dL",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 1,
    encounterNumber: "E066",
    labName: "Aetna Health Labs",
    testName: "Vitamin D Panel",
    testDate: "2024-08-11",
    result1: "25-Hydroxyvitamin D: 28 ng/mL",
    result2: "Vitamin D2: 8 ng/mL",
    result3: "Vitamin D3: 20 ng/mL",
    result4: "Total Vitamin D: 28 ng/mL",
    result5: "Calcium: 9.3 mg/dL",
    result6: "Phosphorus: 3.5 mg/dL",
    result7: "Parathyroid Hormone: 45 pg/mL",
    result8: "Bone Alkaline Phosphatase: 35 U/L",
    resultDate: "2024-08-12",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    encounterNumber: "E007",
    labName: "Quest Diagnostics",
    testName: "Thyroid Panel",
    testDate: "2024-07-10",
    result1: "TSH: 2.5",
    result2: "T4 Free: 1.2",
    result3: "T3 Free: 3.1",
    result4: "Thyroglobulin: 20",
    result5: "TPO Antibodies: 15",
    result6: "Reverse T3: 15",
    result7: "Thyroglobulin Antibodies: 0.9",
    result8: "TSI: 0.4",
    resultDate: "2024-07-11",
  },
  {
    chartNumber: 2,
    encounterNumber: "E008",
    labName: "LabCorp",
    testName: "Liver Function Test",
    testDate: "2024-07-12",
    result1: "AST: 22",
    result2: "ALT: 30",
    result3: "ALP: 65",
    result4: "Total Bilirubin: 0.8",
    result5: "Albumin: 4.2",
    result6: "Total Protein: 7.1",
    result7: "GGT: 35",
    result8: "LDH: 180",
    resultDate: "2024-07-13",
  },
  {
    chartNumber: 2,
    encounterNumber: "E009",
    labName: "Quest Diagnostics",
    testName: "Renal Panel",
    testDate: "2024-07-14",
    result1: "BUN: 17",
    result2: "Creatinine: 1.0",
    result3: "eGFR: 90",
    result4: "Sodium: 139",
    result5: "Potassium: 4.1",
    result6: "Chloride: 101",
    result7: "CO2: 23",
    result8: "Calcium: 9.4",
    resultDate: "2024-07-15",
  },
  {
    chartNumber: 2,
    encounterNumber: "E010",
    labName: "Quest Diagnostics",
    testName: "Liver Function Test",
    testDate: "2024-09-25",
    result1: "AST: 22",
    result2: "ALT: 25",
    result3: "Alkaline Phosphatase: 75",
    result4: "Bilirubin: 0.8",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-09-26",
  },
  {
    chartNumber: 2,
    encounterNumber: "E011",
    labName: "LabCorp",
    testName: "Kidney Function Test",
    testDate: "2024-09-30",
    result1: "BUN: 18",
    result2: "Creatinine: 1.1",
    result3: "GFR: 90",
    result4: "Urine Protein: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-10-01",
  },
  {
    chartNumber: 2,
    encounterNumber: "E012",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-10-05",
    result1: "Total Cholesterol: 185",
    result2: "HDL: 60",
    result3: "LDL: 110",
    result4: "Triglycerides: 140",
    result5: "VLDL: 20",
    result6: "Non-HDL: 125",
    result7: "Chol/HDL Ratio: 3.1",
    result8: "Glucose: 88",
    resultDate: "2024-10-06",
  },
  {
    chartNumber: 2,
    encounterNumber: "E067",
    labName: "Quest Diagnostics",
    testName: "Hepatic Function Panel",
    testDate: "2024-08-01",
    result1: "AST: 25 U/L",
    result2: "ALT: 30 U/L",
    result3: "Alkaline Phosphatase: 95 U/L",
    result4: "Bilirubin Total: 1.2 mg/dL",
    result5: "Bilirubin Direct: 0.3 mg/dL",
    result6: "Albumin: 4.3 g/dL",
    result7: "Total Protein: 7.5 g/dL",
    result8: "GGT: 40 U/L",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 2,
    encounterNumber: "E068",
    labName: "LabCorp",
    testName: "Iron Studies",
    testDate: "2024-08-03",
    result1: "Serum Iron: 120 µg/dL",
    result2: "Total Iron Binding Capacity: 320 µg/dL",
    result3: "Transferrin Saturation: 37%",
    result4: "Ferritin: 80 ng/mL",
    result5: "UIBC: 200 µg/dL",
    result6: "Iron Binding Capacity: 300 µg/dL",
    result7: "Hemoglobin: 13.4 g/dL",
    result8: "Hematocrit: 40.0%",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 2,
    encounterNumber: "E069",
    labName: "BioReference Labs",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-05",
    result1: "Sodium: 140 mmol/L",
    result2: "Potassium: 4.0 mmol/L",
    result3: "Chloride: 102 mmol/L",
    result4: "CO2: 23 mmol/L",
    result5: "BUN: 16 mg/dL",
    result6: "Creatinine: 0.9 mg/dL",
    result7: "Glucose: 95 mg/dL",
    result8: "Calcium: 9.4 mg/dL",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 2,
    encounterNumber: "E070",
    labName: "Mayo Clinic Laboratories",
    testName: "Vitamin B12 and Folate",
    testDate: "2024-08-07",
    result1: "Vitamin B12: 500 pg/mL",
    result2: "Folate: 10 ng/mL",
    result3: "Homocysteine: 9 µmol/L",
    result4: "Methylmalonic Acid: 0.2 µmol/L",
    result5: "Serum Iron: 110 µg/dL",
    result6: "Transferrin: 250 mg/dL",
    result7: "Vitamin B6: 10 µg/dL",
    result8: "Vitamin D: 30 ng/mL",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 2,
    encounterNumber: "E071",
    labName: "Cedars-Sinai Medical Center",
    testName: "Renal Panel",
    testDate: "2024-08-09",
    result1: "Sodium: 139 mmol/L",
    result2: "Potassium: 4.2 mmol/L",
    result3: "Chloride: 104 mmol/L",
    result4: "CO2: 24 mmol/L",
    result5: "BUN: 15 mg/dL",
    result6: "Creatinine: 1.1 mg/dL",
    result7: "Calcium: 9.6 mg/dL",
    result8: "Phosphorus: 3.8 mg/dL",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 2,
    encounterNumber: "E072",
    labName: "Aetna Health Labs",
    testName: "Hemoglobin A1c",
    testDate: "2024-08-11",
    result1: "Hemoglobin A1c: 6.3%",
    result2: "Fasting Glucose: 105 mg/dL",
    result3: "Postprandial Glucose: 140 mg/dL",
    result4: "Fructosamine: 250 µmol/L",
    result5: "Insulin: 12 µU/mL",
    result6: "C-Peptide: 1.5 ng/mL",
    result7: "Beta-Hydroxybutyrate: 0.5 mmol/L",
    result8: "LDL Cholesterol: 130 mg/dL",
    resultDate: "2024-08-12",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    encounterNumber: "E013",
    labName: "LabCorp",
    testName: "Iron Studies",
    testDate: "2024-06-15",
    result1: "Serum Iron: 80",
    result2: "TIBC: 350",
    result3: "Ferritin: 60",
    result4: "Transferrin Saturation: 22%",
    result5: "Hemoglobin: 13.6",
    result6: "Hematocrit: 40.5",
    result7: "MCV: 86",
    result8: "MCH: 28",
    resultDate: "2024-06-16",
  },
  {
    chartNumber: 3,
    encounterNumber: "E014",
    labName: "Quest Diagnostics",
    testName: "Vitamin D Test",
    testDate: "2024-06-18",
    result1: "25-Hydroxy Vitamin D: 32",
    result2: "Calcium: 9.3",
    result3: "Phosphorus: 3.5",
    result4: "PTH: 45",
    result5: "Magnesium: 2.0",
    result6: "Alkaline Phosphatase: 70",
    result7: "Vitamin B12: 500",
    result8: "Folate: 8.5",
    resultDate: "2024-06-19",
  },
  {
    chartNumber: 3,
    encounterNumber: "E015",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-06-20",
    result1: "WBC: 6.0",
    result2: "RBC: 4.8",
    result3: "Hemoglobin: 13.7",
    result4: "Hematocrit: 40.3",
    result5: "Platelets: 230",
    result6: "MCV: 87",
    result7: "MCH: 29",
    result8: "MCHC: 34",
    resultDate: "2024-06-21",
  },
  {
    chartNumber: 3,
    encounterNumber: "E016",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-10-10",
    result1: "WBC: 6.0",
    result2: "RBC: 4.8",
    result3: "Hemoglobin: 13.8",
    result4: "Hematocrit: 41.0",
    result5: "Platelets: 230",
    result6: "MCV: 86",
    result7: "MCH: 30",
    result8: "MCHC: 34.5",
    resultDate: "2024-10-11",
  },
  {
    chartNumber: 3,
    encounterNumber: "E017",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-10-15",
    result1: "TSH: 2.7",
    result2: "Free T4: 1.0",
    result3: "Free T3: 2.9",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-10-16",
  },
  {
    chartNumber: 3,
    encounterNumber: "E018",
    labName: "LabCorp",
    testName: "Vitamin D Test",
    testDate: "2024-10-20",
    result1: "Vitamin D: 32",
    result2: "Calcium: 9.1",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-10-21",
  },
  {
    chartNumber: 3,
    encounterNumber: "E073",
    labName: "Quest Diagnostics",
    testName: "Prostate-Specific Antigen (PSA)",
    testDate: "2024-08-01",
    result1: "PSA Total: 2.5 ng/mL",
    result2: "Free PSA: 0.8 ng/mL",
    result3: "PSA Ratio: 32%",
    result4: "Percent Free PSA: 32%",
    result5: "PSA Velocity: 0.1 ng/mL/year",
    result6: "PSA Density: 0.1 ng/mL/cc",
    result7: "Free PSA/Total PSA Ratio: 0.32",
    result8: "Historical PSA Level: 2.4 ng/mL",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 3,
    encounterNumber: "E074",
    labName: "LabCorp",
    testName: "Coagulation Panel",
    testDate: "2024-08-03",
    result1: "PT: 12.5 seconds",
    result2: "INR: 1.0",
    result3: "PTT: 30.0 seconds",
    result4: "Fibrinogen: 300 mg/dL",
    result5: "Platelet Count: 250 x10^3/µL",
    result6: "D-Dimer: 0.5 µg/mL",
    result7: "Thrombin Time: 14.0 seconds",
    result8: "Activated Partial Thromboplastin Time: 31.0 seconds",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 3,
    encounterNumber: "E075",
    labName: "BioReference Labs",
    testName: "Celiac Disease Panel",
    testDate: "2024-08-05",
    result1: "Anti-TTG IgA: 10 U/mL",
    result2: "Anti-TTG IgG: 8 U/mL",
    result3: "Anti-DGP IgA: 15 U/mL",
    result4: "Anti-DGP IgG: 12 U/mL",
    result5: "Anti-EMA IgA: 5 U/mL",
    result6: "Total IgA: 150 mg/dL",
    result7: "Gluten-Free Diet Antibodies: Negative",
    result8: "Genetic Testing: HLA-DQ2 Positive",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 3,
    encounterNumber: "E076",
    labName: "Mayo Clinic Laboratories",
    testName: "Rheumatoid Factor Panel",
    testDate: "2024-08-07",
    result1: "Rheumatoid Factor: 20 IU/mL",
    result2: "Anti-CCP Antibodies: 50 U/mL",
    result3: "ESR: 20 mm/hr",
    result4: "CRP: 2.0 mg/dL",
    result5: "Anti-MCV Antibodies: 30 U/mL",
    result6: "Anti-Smith Antibodies: Negative",
    result7: "Anti-DNA Antibodies: 15 U/mL",
    result8: "Complement C3: 120 mg/dL",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 3,
    encounterNumber: "E077",
    labName: "Cedars-Sinai Medical Center",
    testName: "Cardiac Enzyme Panel",
    testDate: "2024-08-09",
    result1: "Troponin I: 0.05 ng/mL",
    result2: "Troponin T: 0.06 ng/mL",
    result3: "CK-MB: 5.0 ng/mL",
    result4: "Myoglobin: 80 ng/mL",
    result5: "Total CK: 120 U/L",
    result6: "LDH: 180 U/L",
    result7: "BNP: 50 pg/mL",
    result8: "CRP: 1.5 mg/dL",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 3,
    encounterNumber: "E078",
    labName: "Aetna Health Labs",
    testName: "Allergy Panel",
    testDate: "2024-08-11",
    result1: "IgE Total: 120 IU/mL",
    result2: "Dust Mites: Positive",
    result3: "Pollen: Negative",
    result4: "Mold: Positive",
    result5: "Pet Dander: Negative",
    result6: "Food Allergies: Negative",
    result7: "Bee Venom: Positive",
    result8: "Latex: Negative",
    resultDate: "2024-08-12",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    encounterNumber: "E019",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-05-10",
    result1: "Total Cholesterol: 200",
    result2: "HDL: 50",
    result3: "LDL: 130",
    result4: "Triglycerides: 150",
    result5: "VLDL: 20",
    result6: "Non-HDL: 150",
    result7: "Chol/HDL Ratio: 4.0",
    result8: "Glucose: 95",
    resultDate: "2024-05-11",
  },
  {
    chartNumber: 4,
    encounterNumber: "E020",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-05-12",
    result1: "Sodium: 138",
    result2: "Potassium: 4.0",
    result3: "Chloride: 100",
    result4: "CO2: 25",
    result5: "BUN: 16",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 94",
    result8: "Calcium: 9.6",
    resultDate: "2024-05-13",
  },
  {
    chartNumber: 4,
    encounterNumber: "E021",
    labName: "Quest Diagnostics",
    testName: "Renal Function Test",
    testDate: "2024-05-14",
    result1: "BUN: 17",
    result2: "Creatinine: 1.1",
    result3: "eGFR: 89",
    result4: "Sodium: 140",
    result5: "Potassium: 4.3",
    result6: "Chloride: 102",
    result7: "CO2: 24",
    result8: "Calcium: 9.4",
    resultDate: "2024-05-15",
  },
  {
    chartNumber: 4,
    encounterNumber: "E022",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-10-25",
    result1: "Sodium: 137",
    result2: "Potassium: 4.1",
    result3: "Chloride: 101",
    result4: "CO2: 26",
    result5: "BUN: 19",
    result6: "Creatinine: 1.2",
    result7: "Glucose: 91",
    result8: "Calcium: 9.3",
    resultDate: "2024-10-26",
  },
  {
    chartNumber: 4,
    encounterNumber: "E023",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-11-01",
    result1: "WBC: 6.2",
    result2: "RBC: 4.9",
    result3: "Hemoglobin: 13.9",
    result4: "Hematocrit: 41.2",
    result5: "Platelets: 225",
    result6: "MCV: 85",
    result7: "MCH: 29.5",
    result8: "MCHC: 34.2",
    resultDate: "2024-11-02",
  },
  {
    chartNumber: 4,
    encounterNumber: "E024",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-11-05",
    result1: "Total Cholesterol: 180",
    result2: "HDL: 58",
    result3: "LDL: 115",
    result4: "Triglycerides: 135",
    result5: "VLDL: 22",
    result6: "Non-HDL: 122",
    result7: "Chol/HDL Ratio: 3.2",
    result8: "Glucose: 89",
    resultDate: "2024-11-06",
  },
  {
    chartNumber: 4,
    encounterNumber: "E079",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-08-01",
    result1: "TSH: 2.0 µIU/mL",
    result2: "Free T4: 1.2 ng/dL",
    result3: "Free T3: 3.2 pg/mL",
    result4: "Total T4: 8.5 µg/dL",
    result5: "Total T3: 100 ng/dL",
    result6: "Thyroid Antibodies: Negative",
    result7: "Reverse T3: 20 ng/dL",
    result8: "Thyroglobulin: 30 ng/mL",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 4,
    encounterNumber: "E080",
    labName: "LabCorp",
    testName: "Lipid Panel",
    testDate: "2024-08-03",
    result1: "Total Cholesterol: 190 mg/dL",
    result2: "HDL: 50 mg/dL",
    result3: "LDL: 120 mg/dL",
    result4: "Triglycerides: 100 mg/dL",
    result5: "Total/HDL Ratio: 3.8",
    result6: "Non-HDL Cholesterol: 140 mg/dL",
    result7: "Apolipoprotein B: 80 mg/dL",
    result8: "Apolipoprotein A1: 120 mg/dL",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 4,
    encounterNumber: "E081",
    labName: "BioReference Labs",
    testName: "Hemoglobin Electrophoresis",
    testDate: "2024-08-05",
    result1: "Hemoglobin A: 95%",
    result2: "Hemoglobin A2: 3.0%",
    result3: "Hemoglobin F: 1.0%",
    result4: "Hemoglobin S: 0%",
    result5: "Hemoglobin C: 0%",
    result6: "Hemoglobin E: 0%",
    result7: "Hemoglobin D: 0%",
    result8: "Hemoglobin G: 0%",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 4,
    encounterNumber: "E082",
    labName: "Mayo Clinic Laboratories",
    testName: "Sex Hormone Panel",
    testDate: "2024-08-07",
    result1: "Testosterone Total: 600 ng/dL",
    result2: "Testosterone Free: 50 pg/mL",
    result3: "Estradiol: 30 pg/mL",
    result4: "DHEA-S: 150 µg/dL",
    result5: "LH: 6 IU/L",
    result6: "FSH: 5 IU/L",
    result7: "Prolactin: 10 ng/mL",
    result8: "SHBG: 40 nmol/L",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 4,
    encounterNumber: "E083",
    labName: "Cedars-Sinai Medical Center",
    testName: "Metabolic Syndrome Panel",
    testDate: "2024-08-09",
    result1: "Waist Circumference: 35 inches",
    result2: "BMI: 24 kg/m²",
    result3: "Blood Pressure: 120/80 mmHg",
    result4: "Fasting Glucose: 100 mg/dL",
    result5: "Triglycerides: 150 mg/dL",
    result6: "HDL Cholesterol: 45 mg/dL",
    result7: "LDL Cholesterol: 130 mg/dL",
    result8: "HbA1c: 5.6%",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 4,
    encounterNumber: "E084",
    labName: "Aetna Health Labs",
    testName: "Autoimmune Panel",
    testDate: "2024-08-11",
    result1: "ANA: 1:160",
    result2: "Anti-dsDNA: 15 IU/mL",
    result3: "Anti-Smith: Negative",
    result4: "Anti-RNP: 20 IU/mL",
    result5: "Anti-Ro/SSA: 25 IU/mL",
    result6: "Anti-La/SSB: 10 IU/mL",
    result7: "Anti-Jo-1: Negative",
    result8: "Anti-SCL-70: 30 IU/mL",
    resultDate: "2024-08-12",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    encounterNumber: "E025",
    labName: "LabCorp",
    testName: "Thyroid Panel",
    testDate: "2024-04-10",
    result1: "TSH: 2.4",
    result2: "T4 Free: 1.1",
    result3: "T3 Free: 3.0",
    result4: "Thyroglobulin: 19",
    result5: "TPO Antibodies: 14",
    result6: "Reverse T3: 14",
    result7: "Thyroglobulin Antibodies: 0.8",
    result8: "TSI: 0.3",
    resultDate: "2024-04-11",
  },
  {
    chartNumber: 5,
    encounterNumber: "E026",
    labName: "Quest Diagnostics",
    testName: "Liver Function Test",
    testDate: "2024-04-12",
    result1: "AST: 21",
    result2: "ALT: 29",
    result3: "ALP: 64",
    result4: "Total Bilirubin: 0.7",
    result5: "Albumin: 4.1",
    result6: "Total Protein: 7.0",
    result7: "GGT: 34",
    result8: "LDH: 179",
    resultDate: "2024-04-13",
  },
  {
    chartNumber: 5,
    encounterNumber: "E027",
    labName: "LabCorp",
    testName: "Iron Studies",
    testDate: "2024-04-14",
    result1: "Serum Iron: 79",
    result2: "TIBC: 349",
    result3: "Ferritin: 59",
    result4: "Transferrin Saturation: 21%",
    result5: "Hemoglobin: 13.4",
    result6: "Hematocrit: 40.1",
    result7: "MCV: 85",
    result8: "MCH: 27",
    resultDate: "2024-04-15",
  },
  {
    chartNumber: 5,
    encounterNumber: "E028",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-11-10",
    result1: "Sodium: 139",
    result2: "Potassium: 4.3",
    result3: "Chloride: 102",
    result4: "CO2: 23",
    result5: "BUN: 20",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 90",
    result8: "Calcium: 9.6",
    resultDate: "2024-11-11",
  },
  {
    chartNumber: 5,
    encounterNumber: "E029",
    labName: "Quest Diagnostics",
    testName: "Liver Function Test",
    testDate: "2024-11-15",
    result1: "AST: 23",
    result2: "ALT: 27",
    result3: "Alkaline Phosphatase: 80",
    result4: "Bilirubin: 0.9",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-11-16",
  },
  {
    chartNumber: 5,
    encounterNumber: "E030",
    labName: "LabCorp",
    testName: "Kidney Function Test",
    testDate: "2024-11-20",
    result1: "BUN: 19",
    result2: "Creatinine: 1.1",
    result3: "GFR: 88",
    result4: "Urine Protein: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-11-21",
  },
  {
    chartNumber: 5,
    encounterNumber: "E085",
    labName: "Quest Diagnostics",
    testName: "Hepatic Function Panel",
    testDate: "2024-08-01",
    result1: "ALT: 35 U/L",
    result2: "AST: 30 U/L",
    result3: "ALP: 80 U/L",
    result4: "Bilirubin Total: 1.2 mg/dL",
    result5: "Bilirubin Direct: 0.3 mg/dL",
    result6: "Albumin: 4.2 g/dL",
    result7: "Total Protein: 7.0 g/dL",
    result8: "Gamma-GT: 20 U/L",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 5,
    encounterNumber: "E086",
    labName: "LabCorp",
    testName: "Vitamin D Panel",
    testDate: "2024-08-03",
    result1: "25-Hydroxyvitamin D: 40 ng/mL",
    result2: "Vitamin D2: 5 ng/mL",
    result3: "Vitamin D3: 35 ng/mL",
    result4: "Calcium: 9.2 mg/dL",
    result5: "Phosphorus: 3.5 mg/dL",
    result6: "PTH: 40 pg/mL",
    result7: "Magnesium: 2.1 mg/dL",
    result8: "Vitamin D Binding Protein: 50 µg/mL",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 5,
    encounterNumber: "E087",
    labName: "BioReference Labs",
    testName: "Iron Studies",
    testDate: "2024-08-05",
    result1: "Serum Iron: 70 µg/dL",
    result2: "Total Iron Binding Capacity (TIBC): 300 µg/dL",
    result3: "Transferrin Saturation: 23%",
    result4: "Ferritin: 150 ng/mL",
    result5: "UIBC: 230 µg/dL",
    result6: "Free Erythrocyte Protoporphyrin: 35 µg/dL",
    result7: "Hematocrit: 41%",
    result8: "Hemoglobin: 13.0 g/dL",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 5,
    encounterNumber: "E088",
    labName: "Mayo Clinic Laboratories",
    testName: "Genetic Panel for Hereditary Cancer",
    testDate: "2024-08-07",
    result1: "BRCA1: Negative",
    result2: "BRCA2: Negative",
    result3: "TP53: Negative",
    result4: "MLH1: Negative",
    result5: "MSH2: Negative",
    result6: "MSH6: Negative",
    result7: "PMS2: Negative",
    result8: "CDH1: Negative",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 5,
    encounterNumber: "E089",
    labName: "Cedars-Sinai Medical Center",
    testName: "Bone Density Test",
    testDate: "2024-08-09",
    result1: "Lumbar Spine BMD: 1.2 g/cm²",
    result2: "Femoral Neck BMD: 1.0 g/cm²",
    result3: "Total Hip BMD: 1.1 g/cm²",
    result4: "Z-Score: 0.5",
    result5: "T-Score: -1.0",
    result6: "Fracture Risk: Low",
    result7: "Bone Turnover Markers: Normal",
    result8: "Vertebral Fractures: None",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 5,
    encounterNumber: "E090",
    labName: "Aetna Health Labs",
    testName: "Urinalysis",
    testDate: "2024-08-11",
    result1: "Color: Pale Yellow",
    result2: "Clarity: Clear",
    result3: "Specific Gravity: 1.015",
    result4: "pH: 6.0",
    result5: "Protein: Negative",
    result6: "Glucose: Negative",
    result7: "Ketones: Negative",
    result8: "Leukocyte Esterase: Negative",
    resultDate: "2024-08-12",
  },

  // Chart Number 6
  {
    chartNumber: 6,
    encounterNumber: "E031",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-08-01",
    result1: "WBC: 5.8",
    result2: "RBC: 4.5",
    result3: "Hemoglobin: 13.2",
    result4: "Hematocrit: 39.8",
    result5: "Platelets: 210",
    result6: "MCV: 84",
    result7: "MCH: 28.5",
    result8: "MCHC: 33.8",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 6,
    encounterNumber: "E032",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-08-05",
    result1: "Total Cholesterol: 188",
    result2: "HDL: 53",
    result3: "LDL: 116",
    result4: "Triglycerides: 132",
    result5: "VLDL: 18",
    result6: "Non-HDL: 135",
    result7: "Chol/HDL Ratio: 3.5",
    result8: "Glucose: 89",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 6,
    encounterNumber: "E033",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-10",
    result1: "Sodium: 138",
    result2: "Potassium: 4.3",
    result3: "Chloride: 101",
    result4: "CO2: 23",
    result5: "BUN: 17",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 95",
    result8: "Calcium: 9.5",
    resultDate: "2024-08-11",
  },
  {
    chartNumber: 6,
    encounterNumber: "E034",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-08-15",
    result1: "TSH: 2.3",
    result2: "Free T4: 1.1",
    result3: "Free T3: 2.8",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-16",
  },
  {
    chartNumber: 6,
    encounterNumber: "E035",
    labName: "LabCorp",
    testName: "Vitamin D Test",
    testDate: "2024-08-20",
    result1: "Vitamin D: 28",
    result2: "Calcium: 9.3",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-21",
  },
  {
    chartNumber: 6,
    encounterNumber: "E036",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-08-25",
    result1: "Sodium: 137",
    result2: "Potassium: 4.1",
    result3: "Chloride: 100",
    result4: "CO2: 24",
    result5: "BUN: 16",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 92",
    result8: "Calcium: 9.4",
    resultDate: "2024-08-26",
  },
  {
    chartNumber: 6,
    encounterNumber: "E091",
    labName: "Quest Diagnostics",
    testName: "Electrolyte Panel",
    testDate: "2024-08-01",
    result1: "Sodium: 140 mmol/L",
    result2: "Potassium: 4.1 mmol/L",
    result3: "Chloride: 102 mmol/L",
    result4: "Bicarbonate: 24 mmol/L",
    result5: "Calcium: 9.0 mg/dL",
    result6: "Magnesium: 2.0 mg/dL",
    result7: "Phosphate: 3.4 mg/dL",
    result8: "Anion Gap: 12 mmol/L",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 6,
    encounterNumber: "E092",
    labName: "LabCorp",
    testName: "Complete Metabolic Panel",
    testDate: "2024-08-03",
    result1: "Glucose: 95 mg/dL",
    result2: "BUN: 18 mg/dL",
    result3: "Creatinine: 0.9 mg/dL",
    result4: "Calcium: 9.5 mg/dL",
    result5: "Sodium: 139 mmol/L",
    result6: "Potassium: 4.0 mmol/L",
    result7: "Chloride: 103 mmol/L",
    result8: "CO2: 23 mmol/L",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 6,
    encounterNumber: "E093",
    labName: "BioReference Labs",
    testName: "Celiac Disease Panel",
    testDate: "2024-08-05",
    result1: "tTG-IgA: Negative",
    result2: "EMA-IgA: Negative",
    result3: "Total Serum IgA: Normal",
    result4: "Deamidated Gliadin Antibodies: Negative",
    result5: "Anti-Endomysial Antibodies: Negative",
    result6: "Anti-Gliadin Antibodies: Negative",
    result7: "Genetic Markers: No risk identified",
    result8: "Histology: Normal",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 6,
    encounterNumber: "E094",
    labName: "Mayo Clinic Laboratories",
    testName: "Renal Function Panel",
    testDate: "2024-08-07",
    result1: "Creatinine: 1.0 mg/dL",
    result2: "BUN: 16 mg/dL",
    result3: "GFR: 90 mL/min/1.73m²",
    result4: "Sodium: 140 mmol/L",
    result5: "Potassium: 4.2 mmol/L",
    result6: "Calcium: 9.3 mg/dL",
    result7: "Phosphate: 3.5 mg/dL",
    result8: "CO2: 23 mmol/L",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 6,
    encounterNumber: "E095",
    labName: "Cedars-Sinai Medical Center",
    testName: "Cardiac Biomarkers Panel",
    testDate: "2024-08-09",
    result1: "Troponin I: 0.01 ng/mL",
    result2: "BNP: 100 pg/mL",
    result3: "CK-MB: 3 ng/mL",
    result4: "Myoglobin: 80 ng/mL",
    result5: "LDH: 180 U/L",
    result6: "HS-CRP: 1.5 mg/L",
    result7: "Echocardiogram: Normal",
    result8: "ECG: Normal",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 6,
    encounterNumber: "E096",
    labName: "Aetna Health Labs",
    testName: "Coagulation Profile",
    testDate: "2024-08-11",
    result1: "PT: 12.5 seconds",
    result2: "INR: 1.0",
    result3: "aPTT: 30 seconds",
    result4: "Fibrinogen: 350 mg/dL",
    result5: "D-Dimer: 0.5 µg/mL",
    result6: "Platelet Count: 250,000/µL",
    result7: "Antithrombin III: 100%",
    result8: "Protein C: 90%",
    resultDate: "2024-08-12",
  },

  // Chart Number 7
  {
    chartNumber: 7,
    encounterNumber: "E037",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-09-01",
    result1: "WBC: 6.0",
    result2: "RBC: 4.6",
    result3: "Hemoglobin: 13.4",
    result4: "Hematocrit: 40.1",
    result5: "Platelets: 215",
    result6: "MCV: 85",
    result7: "MCH: 29",
    result8: "MCHC: 34",
    resultDate: "2024-09-02",
  },
  {
    chartNumber: 7,
    encounterNumber: "E038",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-09-05",
    result1: "Total Cholesterol: 182",
    result2: "HDL: 54",
    result3: "LDL: 119",
    result4: "Triglycerides: 128",
    result5: "VLDL: 19",
    result6: "Non-HDL: 128",
    result7: "Chol/HDL Ratio: 3.4",
    result8: "Glucose: 91",
    resultDate: "2024-09-06",
  },
  {
    chartNumber: 7,
    encounterNumber: "E039",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-09-10",
    result1: "Sodium: 139",
    result2: "Potassium: 4.2",
    result3: "Chloride: 102",
    result4: "CO2: 23",
    result5: "BUN: 18",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 94",
    result8: "Calcium: 9.6",
    resultDate: "2024-09-11",
  },
  {
    chartNumber: 7,
    encounterNumber: "E040",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-09-15",
    result1: "TSH: 2.4",
    result2: "Free T4: 1.0",
    result3: "Free T3: 3.0",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-09-16",
  },
  {
    chartNumber: 7,
    encounterNumber: "E041",
    labName: "LabCorp",
    testName: "Vitamin D Test",
    testDate: "2024-09-20",
    result1: "Vitamin D: 29",
    result2: "Calcium: 9.2",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-09-21",
  },
  {
    chartNumber: 7,
    encounterNumber: "E042",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-09-25",
    result1: "Sodium: 136",
    result2: "Potassium: 4.0",
    result3: "Chloride: 99",
    result4: "CO2: 22",
    result5: "BUN: 15",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 93",
    result8: "Calcium: 9.5",
    resultDate: "2024-09-26",
  },
  {
    chartNumber: 7,
    encounterNumber: "E097",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-08-01",
    result1: "TSH: 2.5 µIU/mL",
    result2: "Free T4: 1.2 ng/dL",
    result3: "Free T3: 3.0 pg/mL",
    result4: "Total T4: 7.0 µg/dL",
    result5: "Total T3: 120 ng/dL",
    result6: "Thyroid Peroxidase Antibodies: Negative",
    result7: "Thyroglobulin Antibodies: Negative",
    result8: "Thyroid Stimulating Immunoglobulin: Normal",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 7,
    encounterNumber: "E098",
    labName: "LabCorp",
    testName: "Lipid Panel",
    testDate: "2024-08-03",
    result1: "Total Cholesterol: 200 mg/dL",
    result2: "LDL Cholesterol: 120 mg/dL",
    result3: "HDL Cholesterol: 60 mg/dL",
    result4: "Triglycerides: 150 mg/dL",
    result5: "Chol/HDL Ratio: 3.3",
    result6: "LDL/HDL Ratio: 2.0",
    result7: "Non-HDL Cholesterol: 140 mg/dL",
    result8: "Apolipoprotein B: 90 mg/dL",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 7,
    encounterNumber: "E099",
    labName: "BioReference Labs",
    testName: "Hemoglobin A1c",
    testDate: "2024-08-05",
    result1: "Hemoglobin A1c: 6.2%",
    result2: "Estimated Average Glucose: 130 mg/dL",
    result3: "Fasting Blood Glucose: 100 mg/dL",
    result4: "2-Hour Postprandial Glucose: 140 mg/dL",
    result5: "Random Blood Glucose: 110 mg/dL",
    result6: "Fructosamine: 220 µmol/L",
    result7: "Glycated Albumin: 15%",
    result8: "Insulin: 12 µU/mL",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 7,
    encounterNumber: "E100",
    labName: "Mayo Clinic Laboratories",
    testName: "Autoimmune Panel",
    testDate: "2024-08-07",
    result1: "ANA: Negative",
    result2: "Anti-dsDNA: Negative",
    result3: "Anti-Smith: Negative",
    result4: "Anti-Ro: Negative",
    result5: "Anti-La: Negative",
    result6: "Rheumatoid Factor: 14 IU/mL",
    result7: "Anti-CCP: Negative",
    result8: "Anti-U1 RNP: Negative",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 7,
    encounterNumber: "E101",
    labName: "Cedars-Sinai Medical Center",
    testName: "Vitamin B12 and Folate",
    testDate: "2024-08-09",
    result1: "Vitamin B12: 500 pg/mL",
    result2: "Folate: 15 ng/mL",
    result3: "Methylmalonic Acid: 200 nmol/L",
    result4: "Homocysteine: 10 µmol/L",
    result5: "Red Cell Folate: 500 ng/mL",
    result6: "Serum Cobalamin: 400 pg/mL",
    result7: "RBC Folate: 450 ng/mL",
    result8: "Total B12 Binding Capacity: 120 µg/mL",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 7,
    encounterNumber: "E102",
    labName: "Aetna Health Labs",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-08-11",
    result1: "Glucose: 92 mg/dL",
    result2: "BUN: 17 mg/dL",
    result3: "Creatinine: 0.8 mg/dL",
    result4: "Sodium: 141 mmol/L",
    result5: "Potassium: 4.0 mmol/L",
    result6: "Chloride: 104 mmol/L",
    result7: "CO2: 22 mmol/L",
    result8: "Calcium: 9.4 mg/dL",
    resultDate: "2024-08-12",
  },

  // Chart Number 8
  {
    chartNumber: 8,
    encounterNumber: "E043",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-10-01",
    result1: "WBC: 5.9",
    result2: "RBC: 4.4",
    result3: "Hemoglobin: 13.1",
    result4: "Hematocrit: 39.5",
    result5: "Platelets: 205",
    result6: "MCV: 84",
    result7: "MCH: 28",
    result8: "MCHC: 33.5",
    resultDate: "2024-10-02",
  },
  {
    chartNumber: 8,
    encounterNumber: "E044",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-10-05",
    result1: "Total Cholesterol: 180",
    result2: "HDL: 56",
    result3: "LDL: 115",
    result4: "Triglycerides: 125",
    result5: "VLDL: 20",
    result6: "Non-HDL: 124",
    result7: "Chol/HDL Ratio: 3.2",
    result8: "Glucose: 90",
    resultDate: "2024-10-06",
  },
  {
    chartNumber: 8,
    encounterNumber: "E045",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-10-10",
    result1: "Sodium: 137",
    result2: "Potassium: 4.2",
    result3: "Chloride: 100",
    result4: "CO2: 24",
    result5: "BUN: 16",
    result6: "Creatinine: 1.2",
    result7: "Glucose: 91",
    result8: "Calcium: 9.7",
    resultDate: "2024-10-11",
  },
  {
    chartNumber: 8,
    encounterNumber: "E046",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-10-15",
    result1: "TSH: 2.5",
    result2: "Free T4: 1.2",
    result3: "Free T3: 2.9",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-10-16",
  },
  {
    chartNumber: 8,
    encounterNumber: "E047",
    labName: "LabCorp",
    testName: "Vitamin D Test",
    testDate: "2024-10-20",
    result1: "Vitamin D: 30",
    result2: "Calcium: 9.4",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-10-21",
  },
  {
    chartNumber: 8,
    encounterNumber: "E048",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-10-25",
    result1: "Sodium: 138",
    result2: "Potassium: 4.3",
    result3: "Chloride: 101",
    result4: "CO2: 23",
    result5: "BUN: 17",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 92",
    result8: "Calcium: 9.6",
    resultDate: "2024-10-26",
  },
  {
    chartNumber: 8,
    encounterNumber: "E103",
    labName: "Quest Diagnostics",
    testName: "Allergy Panel",
    testDate: "2024-08-01",
    result1: "IgE Total: 150 IU/mL",
    result2: "Pollen Allergy: Positive",
    result3: "Dust Mite Allergy: Negative",
    result4: "Mold Allergy: Positive",
    result5: "Pet Dander Allergy: Negative",
    result6: "Food Allergies: None detected",
    result7: "Skin Prick Test: Positive for Pollen",
    result8: "Serum Specific IgE: Elevated for Pollen",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 8,
    encounterNumber: "E104",
    labName: "LabCorp",
    testName: "Hepatic Function Panel",
    testDate: "2024-08-03",
    result1: "AST: 22 U/L",
    result2: "ALT: 25 U/L",
    result3: "ALP: 90 U/L",
    result4: "Total Bilirubin: 1.0 mg/dL",
    result5: "Direct Bilirubin: 0.3 mg/dL",
    result6: "Albumin: 4.2 g/dL",
    result7: "Total Protein: 7.5 g/dL",
    result8: "Gamma-GT: 30 U/L",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 8,
    encounterNumber: "E105",
    labName: "BioReference Labs",
    testName: "Prostate-Specific Antigen (PSA)",
    testDate: "2024-08-05",
    result1: "PSA Total: 2.5 ng/mL",
    result2: "Free PSA: 0.8 ng/mL",
    result3: "PSA Ratio: 32%",
    result4: "PSA Velocity: 0.1 ng/mL/year",
    result5: "Prostate Health Index: 35",
    result6: "Digital Rectal Exam: Normal",
    result7: "Transrectal Ultrasound: Not indicated",
    result8: "PSA Density: 0.1",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 8,
    encounterNumber: "E106",
    labName: "Mayo Clinic Laboratories",
    testName: "Hemoglobin Electrophoresis",
    testDate: "2024-08-07",
    result1: "HbA: 95%",
    result2: "HbS: 2%",
    result3: "HbF: 3%",
    result4: "HbC: 0%",
    result5: "HbA2: 2%",
    result6: "Variant Hemoglobin: None detected",
    result7: "Overall Hemoglobin: Normal",
    result8: "Clinical Interpretation: No hemoglobinopathy",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 8,
    encounterNumber: "E107",
    labName: "Cedars-Sinai Medical Center",
    testName: "Bone Density Scan",
    testDate: "2024-08-09",
    result1: "T-Score: -1.0",
    result2: "Z-Score: 0.5",
    result3: "Lumbar Spine BMD: 1.2 g/cm²",
    result4: "Femoral Neck BMD: 1.1 g/cm²",
    result5: "Total Hip BMD: 1.15 g/cm²",
    result6: "Bone Quality: Normal",
    result7: "Risk of Osteoporosis: Low",
    result8: "Follow-Up Recommendations: Routine check-up in 2 years",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 8,
    encounterNumber: "E108",
    labName: "Aetna Health Labs",
    testName: "Urinalysis",
    testDate: "2024-08-11",
    result1: "Color: Pale yellow",
    result2: "Clarity: Clear",
    result3: "Specific Gravity: 1.015",
    result4: "pH: 6.0",
    result5: "Protein: Negative",
    result6: "Glucose: Negative",
    result7: "Ketones: Negative",
    result8: "Leukocytes: Negative",
    resultDate: "2024-08-12",
  },

  // Chart Number 9
  {
    chartNumber: 9,
    encounterNumber: "E049",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-11-01",
    result1: "WBC: 5.7",
    result2: "RBC: 4.5",
    result3: "Hemoglobin: 13.3",
    result4: "Hematocrit: 40.0",
    result5: "Platelets: 210",
    result6: "MCV: 85",
    result7: "MCH: 28.5",
    result8: "MCHC: 34",
    resultDate: "2024-11-02",
  },
  {
    chartNumber: 9,
    encounterNumber: "E050",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-11-05",
    result1: "Total Cholesterol: 185",
    result2: "HDL: 55",
    result3: "LDL: 117",
    result4: "Triglycerides: 130",
    result5: "VLDL: 19",
    result6: "Non-HDL: 130",
    result7: "Chol/HDL Ratio: 3.3",
    result8: "Glucose: 88",
    resultDate: "2024-11-06",
  },
  {
    chartNumber: 9,
    encounterNumber: "E051",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-11-10",
    result1: "Sodium: 138",
    result2: "Potassium: 4.4",
    result3: "Chloride: 102",
    result4: "CO2: 24",
    result5: "BUN: 16",
    result6: "Creatinine: 1.2",
    result7: "Glucose: 93",
    result8: "Calcium: 9.5",
    resultDate: "2024-11-11",
  },
  {
    chartNumber: 9,
    encounterNumber: "E052",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-11-15",
    result1: "TSH: 2.6",
    result2: "Free T4: 1.0",
    result3: "Free T3: 2.8",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-11-16",
  },
  {
    chartNumber: 9,
    encounterNumber: "E053",
    labName: "LabCorp",
    testName: "Vitamin D Test",
    testDate: "2024-11-20",
    result1: "Vitamin D: 31",
    result2: "Calcium: 9.3",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-11-21",
  },
  {
    chartNumber: 9,
    encounterNumber: "E054",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-11-25",
    result1: "Sodium: 137",
    result2: "Potassium: 4.2",
    result3: "Chloride: 100",
    result4: "CO2: 22",
    result5: "BUN: 15",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 94",
    result8: "Calcium: 9.4",
    resultDate: "2024-11-26",
  },
  {
    chartNumber: 9,
    encounterNumber: "E109",
    labName: "Quest Diagnostics",
    testName: "Vitamin D Panel",
    testDate: "2024-08-01",
    result1: "25-Hydroxyvitamin D: 30 ng/mL",
    result2: "Vitamin D2: 10 ng/mL",
    result3: "Vitamin D3: 20 ng/mL",
    result4: "Total Vitamin D: 30 ng/mL",
    result5: "PTH: 50 pg/mL",
    result6: "Calcium: 9.5 mg/dL",
    result7: "Phosphorus: 3.5 mg/dL",
    result8: "Bone Density: Normal",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 9,
    encounterNumber: "E110",
    labName: "LabCorp",
    testName: "CBC with Differential",
    testDate: "2024-08-03",
    result1: "WBC: 5.8 x10^3/µL",
    result2: "RBC: 4.6 x10^6/µL",
    result3: "Hemoglobin: 14.2 g/dL",
    result4: "Hematocrit: 43.0%",
    result5: "Platelets: 250 x10^3/µL",
    result6: "Neutrophils: 60%",
    result7: "Lymphocytes: 30%",
    result8: "Monocytes: 7%",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 9,
    encounterNumber: "E111",
    labName: "BioReference Labs",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-08-05",
    result1: "Glucose: 85 mg/dL",
    result2: "BUN: 15 mg/dL",
    result3: "Creatinine: 0.9 mg/dL",
    result4: "Sodium: 142 mmol/L",
    result5: "Potassium: 4.1 mmol/L",
    result6: "Chloride: 103 mmol/L",
    result7: "CO2: 24 mmol/L",
    result8: "Calcium: 9.2 mg/dL",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 9,
    encounterNumber: "E112",
    labName: "Mayo Clinic Laboratories",
    testName: "Iron Studies",
    testDate: "2024-08-07",
    result1: "Serum Iron: 80 µg/dL",
    result2: "Total Iron Binding Capacity: 300 µg/dL",
    result3: "Transferrin Saturation: 27%",
    result4: "Ferritin: 100 ng/mL",
    result5: "Serum Ferritin: 100 ng/mL",
    result6: "Serum Transferrin: 250 mg/dL",
    result7: "UIBC: 220 µg/dL",
    result8: "Total Iron Binding Capacity: 300 µg/dL",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 9,
    encounterNumber: "E113",
    labName: "Cedars-Sinai Medical Center",
    testName: "HIV Test",
    testDate: "2024-08-09",
    result1: "HIV Antibody Test: Negative",
    result2: "HIV RNA Test: Not Detected",
    result3: "HIV-1: Negative",
    result4: "HIV-2: Not Detected",
    result5: "CD4 Count: 800 cells/µL",
    result6: "Viral Load: Undetectable",
    result7: "HIV Genotype: Not Performed",
    result8: "HIV Resistance Testing: Not Indicated",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 9,
    encounterNumber: "E114",
    labName: "Aetna Health Labs",
    testName: "Urine Culture",
    testDate: "2024-08-11",
    result1: "Culture: No growth",
    result2: "Colony Count: <10^4 CFU/mL",
    result3: "Pathogens: None detected",
    result4: "Antibiotic Sensitivity: Not applicable",
    result5: "Leukocyte Esterase: Negative",
    result6: "Nitrites: Negative",
    result7: "pH: 6.0",
    result8: "Specific Gravity: 1.015",
    resultDate: "2024-08-12",
  },

  // Chart Number 10
  {
    chartNumber: 10,
    encounterNumber: "E055",
    labName: "LabCorp",
    testName: "Complete Blood Count",
    testDate: "2024-12-01",
    result1: "WBC: 6.0",
    result2: "RBC: 4.6",
    result3: "Hemoglobin: 13.5",
    result4: "Hematocrit: 40.2",
    result5: "Platelets: 220",
    result6: "MCV: 86",
    result7: "MCH: 29",
    result8: "MCHC: 34",
    resultDate: "2024-12-02",
  },
  {
    chartNumber: 10,
    encounterNumber: "E056",
    labName: "Quest Diagnostics",
    testName: "Lipid Panel",
    testDate: "2024-12-05",
    result1: "Total Cholesterol: 190",
    result2: "HDL: 57",
    result3: "LDL: 121",
    result4: "Triglycerides: 135",
    result5: "VLDL: 22",
    result6: "Non-HDL: 133",
    result7: "Chol/HDL Ratio: 3.3",
    result8: "Glucose: 92",
    resultDate: "2024-12-06",
  },
  {
    chartNumber: 10,
    encounterNumber: "E057",
    labName: "LabCorp",
    testName: "Basic Metabolic Panel",
    testDate: "2024-12-10",
    result1: "Sodium: 139",
    result2: "Potassium: 4.3",
    result3: "Chloride: 103",
    result4: "CO2: 25",
    result5: "BUN: 18",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 90",
    result8: "Calcium: 9.6",
    resultDate: "2024-12-11",
  },
  {
    chartNumber: 10,
    encounterNumber: "E058",
    labName: "Quest Diagnostics",
    testName: "Thyroid Function Test",
    testDate: "2024-12-15",
    result1: "TSH: 2.4",
    result2: "Free T4: 1.1",
    result3: "Free T3: 2.7",
    result4: "Thyroid Antibodies: Negative",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-12-16",
  },
  {
    chartNumber: 10,
    encounterNumber: "E059",
    labName: "LabCorp",
    testName: "Vitamin D Test",
    testDate: "2024-12-20",
    result1: "Vitamin D: 32",
    result2: "Calcium: 9.4",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-12-21",
  },
  {
    chartNumber: 10,
    encounterNumber: "E060",
    labName: "Quest Diagnostics",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-12-25",
    result1: "Sodium: 137",
    result2: "Potassium: 4.1",
    result3: "Chloride: 101",
    result4: "CO2: 23",
    result5: "BUN: 16",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 91",
    result8: "Calcium: 9.5",
    resultDate: "2024-12-26",
  },
  {
    chartNumber: 10,
    encounterNumber: "E115",
    labName: "Quest Diagnostics",
    testName: "Thyroid Panel",
    testDate: "2024-08-01",
    result1: "TSH: 1.8 µIU/mL",
    result2: "Free T4: 1.1 ng/dL",
    result3: "Free T3: 3.2 pg/mL",
    result4: "Total T4: 7.0 µg/dL",
    result5: "Total T3: 100 ng/dL",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 2.0 ng/mL",
    result8: "Thyroid Ultrasound: Not performed",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 10,
    encounterNumber: "E116",
    labName: "LabCorp",
    testName: "Lipid Panel",
    testDate: "2024-08-03",
    result1: "Total Cholesterol: 190 mg/dL",
    result2: "LDL: 120 mg/dL",
    result3: "HDL: 50 mg/dL",
    result4: "Triglycerides: 150 mg/dL",
    result5: "Chol/HDL Ratio: 3.8",
    result6: "Non-HDL Cholesterol: 140 mg/dL",
    result7: "VLDL: 30 mg/dL",
    result8: "Apolipoprotein B: 90 mg/dL",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 10,
    encounterNumber: "E117",
    labName: "BioReference Labs",
    testName: "Hemoglobin A1c",
    testDate: "2024-08-05",
    result1: "Hemoglobin A1c: 5.8%",
    result2: "Average Blood Glucose: 120 mg/dL",
    result3: "Fasting Glucose: 95 mg/dL",
    result4: "Postprandial Glucose: 130 mg/dL",
    result5: "Fructosamine: 200 µmol/L",
    result6: "Glycemic Control: Good",
    result7: "Diabetes Risk: Low",
    result8: "Follow-Up Recommendations: Annual check-up",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 10,
    encounterNumber: "E118",
    labName: "Mayo Clinic Laboratories",
    testName: "Genetic Testing Panel",
    testDate: "2024-08-07",
    result1: "BRCA1: Negative",
    result2: "BRCA2: Negative",
    result3: "TP53: Negative",
    result4: "MLH1: Negative",
    result5: "MSH2: Negative",
    result6: "MSH6: Negative",
    result7: "PMS2: Negative",
    result8: "Genetic Risk: Low",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 10,
    encounterNumber: "E119",
    labName: "Cedars-Sinai Medical Center",
    testName: "Cardiac Stress Test",
    testDate: "2024-08-09",
    result1: "Resting Heart Rate: 70 bpm",
    result2: "Max Heart Rate: 150 bpm",
    result3: "Blood Pressure Response: Normal",
    result4: "Exercise Duration: 10 minutes",
    result5: "Peak Exercise Capacity: 8 METs",
    result6: "ECG Changes: None",
    result7: "Symptoms During Test: None",
    result8: "Test Interpretation: Normal",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 10,
    encounterNumber: "E120",
    labName: "Aetna Health Labs",
    testName: "Nutritional Panel",
    testDate: "2024-08-11",
    result1: "Vitamin B12: 450 pg/mL",
    result2: "Folate: 8.5 ng/mL",
    result3: "Vitamin C: 1.2 mg/dL",
    result4: "Calcium: 9.8 mg/dL",
    result5: "Magnesium: 2.1 mg/dL",
    result6: "Iron: 90 µg/dL",
    result7: "Zinc: 70 µg/dL",
    result8: "Nutritional Status: Adequate",
    resultDate: "2024-08-12",
  },
];
