export const medicationsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    medicationName: "Lisinopril",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "John",
    drLastName: "Doe",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC001",
  },
  {
    chartNumber: 1,
    medicationName: "Metformin",
    startDate: "2024-08-03",
    endDate: "2024-08-17",
    drFirstName: "Jane",
    drLastName: "Smith",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take after meals",
    encounterNumber: "ENC002",
  },
  {
    chartNumber: 1,
    medicationName: "Amlodipine",
    startDate: "2024-08-05",
    endDate: "2024-08-19",
    drFirstName: "Michael",
    drLastName: "Johnson",
    duration: "14 days",
    dose: "5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC003",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    medicationName: "Atorvastatin",
    startDate: "2024-07-10",
    endDate: "2024-07-24",
    drFirstName: "Emily",
    drLastName: "Brown",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take at bedtime",
    encounterNumber: "ENC004",
  },
  {
    chartNumber: 2,
    medicationName: "Omeprazole",
    startDate: "2024-07-12",
    endDate: "2024-07-26",
    drFirstName: "David",
    drLastName: "Wilson",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take before breakfast",
    encounterNumber: "ENC005",
  },
  {
    chartNumber: 2,
    medicationName: "Levothyroxine",
    startDate: "2024-07-14",
    endDate: "2024-07-28",
    drFirstName: "Olivia",
    drLastName: "Taylor",
    duration: "14 days",
    dose: "100",
    doseUnit: "mcg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take on an empty stomach",
    encounterNumber: "ENC006",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    medicationName: "Alprazolam",
    startDate: "2024-06-15",
    endDate: "2024-06-29",
    drFirstName: "Christopher",
    drLastName: "Anderson",
    duration: "14 days",
    dose: "0.5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take as needed for anxiety",
    encounterNumber: "ENC007",
  },
  {
    chartNumber: 3,
    medicationName: "Citalopram",
    startDate: "2024-06-18",
    endDate: "2024-07-02",
    drFirstName: "Sophia",
    drLastName: "Thomas",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor mood changes",
    encounterNumber: "ENC008",
  },
  {
    chartNumber: 3,
    medicationName: "Gabapentin",
    startDate: "2024-06-20",
    endDate: "2024-07-04",
    drFirstName: "Isabella",
    drLastName: "Martinez",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Three times daily",
    route: "PO",
    comments: "Take with water",
    encounterNumber: "ENC009",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    medicationName: "Hydrochlorothiazide",
    startDate: "2024-05-10",
    endDate: "2024-05-24",
    drFirstName: "Liam",
    drLastName: "Garcia",
    duration: "14 days",
    dose: "25",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC010",
  },
  {
    chartNumber: 4,
    medicationName: "Ciprofloxacin",
    startDate: "2024-05-12",
    endDate: "2024-05-26",
    drFirstName: "Mia",
    drLastName: "Rodriguez",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Avoid dairy products",
    encounterNumber: "ENC011",
  },
  {
    chartNumber: 4,
    medicationName: "Prednisone",
    startDate: "2024-05-14",
    endDate: "2024-05-28",
    drFirstName: "Lucas",
    drLastName: "Lee",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Taper dosage as instructed",
    encounterNumber: "ENC012",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    medicationName: "Warfarin",
    startDate: "2024-04-10",
    endDate: "2024-04-24",
    drFirstName: "Amelia",
    drLastName: "Hernandez",
    duration: "14 days",
    dose: "5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor INR levels",
    encounterNumber: "ENC013",
  },
  {
    chartNumber: 5,
    medicationName: "Clindamycin",
    startDate: "2024-04-12",
    endDate: "2024-04-26",
    drFirstName: "James",
    drLastName: "King",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Four times daily",
    route: "PO",
    comments: "Complete the full course",
    encounterNumber: "ENC014",
  },
  {
    chartNumber: 5,
    medicationName: "Metoprolol",
    startDate: "2024-04-14",
    endDate: "2024-04-28",
    drFirstName: "Ava",
    drLastName: "Lopez",
    duration: "14 days",
    dose: "50",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take with or without food",
    encounterNumber: "ENC015",
  },
];
