export const medicationsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    medicationName: "Lisinopril",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "John",
    drLastName: "Doe",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC001",
  },
  {
    chartNumber: 1,
    medicationName: "Metformin",
    startDate: "2024-08-03",
    endDate: "2024-08-17",
    drFirstName: "Jane",
    drLastName: "Smith",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take after meals",
    encounterNumber: "ENC002",
  },
  {
    chartNumber: 1,
    medicationName: "Amlodipine",
    startDate: "2024-08-05",
    endDate: "2024-08-19",
    drFirstName: "Michael",
    drLastName: "Johnson",
    duration: "14 days",
    dose: "5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC003",
  },
  {
    chartNumber: 1,
    medicationName: "Lisinopril",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "John",
    drLastName: "Doe",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC016",
  },
  {
    chartNumber: 1,
    medicationName: "Metformin",
    startDate: "2024-08-03",
    endDate: "2024-08-17",
    drFirstName: "Jane",
    drLastName: "Smith",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take after meals",
    encounterNumber: "ENC017",
  },
  {
    chartNumber: 1,
    medicationName: "Amlodipine",
    startDate: "2024-08-05",
    endDate: "2024-08-19",
    drFirstName: "Michael",
    drLastName: "Johnson",
    duration: "14 days",
    dose: "5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC018",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    medicationName: "Atorvastatin",
    startDate: "2024-07-10",
    endDate: "2024-07-24",
    drFirstName: "Emily",
    drLastName: "Brown",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take at bedtime",
    encounterNumber: "ENC004",
  },
  {
    chartNumber: 2,
    medicationName: "Omeprazole",
    startDate: "2024-07-12",
    endDate: "2024-07-26",
    drFirstName: "David",
    drLastName: "Wilson",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take before breakfast",
    encounterNumber: "ENC005",
  },
  {
    chartNumber: 2,
    medicationName: "Levothyroxine",
    startDate: "2024-07-14",
    endDate: "2024-07-28",
    drFirstName: "Olivia",
    drLastName: "Taylor",
    duration: "14 days",
    dose: "100",
    doseUnit: "mcg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take on an empty stomach",
    encounterNumber: "ENC006",
  },
  {
    chartNumber: 2,
    medicationName: "Atorvastatin",
    startDate: "2024-08-01",
    endDate: "2024-08-14",
    drFirstName: "Emily",
    drLastName: "Brown",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the evening",
    encounterNumber: "ENC019",
  },
  {
    chartNumber: 2,
    medicationName: "Losartan",
    startDate: "2024-08-04",
    endDate: "2024-08-18",
    drFirstName: "David",
    drLastName: "Lee",
    duration: "14 days",
    dose: "50",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC020",
  },
  {
    chartNumber: 2,
    medicationName: "Hydrochlorothiazide",
    startDate: "2024-08-06",
    endDate: "2024-08-20",
    drFirstName: "Susan",
    drLastName: "Wilson",
    duration: "14 days",
    dose: "25",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC021",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    medicationName: "Alprazolam",
    startDate: "2024-06-15",
    endDate: "2024-06-29",
    drFirstName: "Christopher",
    drLastName: "Anderson",
    duration: "14 days",
    dose: "0.5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take as needed for anxiety",
    encounterNumber: "ENC007",
  },
  {
    chartNumber: 3,
    medicationName: "Citalopram",
    startDate: "2024-06-18",
    endDate: "2024-07-02",
    drFirstName: "Sophia",
    drLastName: "Thomas",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor mood changes",
    encounterNumber: "ENC008",
  },
  {
    chartNumber: 3,
    medicationName: "Gabapentin",
    startDate: "2024-06-20",
    endDate: "2024-07-04",
    drFirstName: "Isabella",
    drLastName: "Martinez",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Three times daily",
    route: "PO",
    comments: "Take with water",
    encounterNumber: "ENC009",
  },
  {
    chartNumber: 3,
    medicationName: "Simvastatin",
    startDate: "2024-08-02",
    endDate: "2024-08-16",
    drFirstName: "Karen",
    drLastName: "Moore",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take before bedtime",
    encounterNumber: "ENC022",
  },
  {
    chartNumber: 3,
    medicationName: "Gabapentin",
    startDate: "2024-08-07",
    endDate: "2024-08-21",
    drFirstName: "Robert",
    drLastName: "Taylor",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Three times daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC023",
  },
  {
    chartNumber: 3,
    medicationName: "Omeprazole",
    startDate: "2024-08-09",
    endDate: "2024-08-23",
    drFirstName: "Linda",
    drLastName: "Anderson",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take before meals",
    encounterNumber: "ENC024",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    medicationName: "Hydrochlorothiazide",
    startDate: "2024-05-10",
    endDate: "2024-05-24",
    drFirstName: "Liam",
    drLastName: "Garcia",
    duration: "14 days",
    dose: "25",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC010",
  },
  {
    chartNumber: 4,
    medicationName: "Ciprofloxacin",
    startDate: "2024-05-12",
    endDate: "2024-05-26",
    drFirstName: "Mia",
    drLastName: "Rodriguez",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Avoid dairy products",
    encounterNumber: "ENC011",
  },
  {
    chartNumber: 4,
    medicationName: "Prednisone",
    startDate: "2024-05-14",
    endDate: "2024-05-28",
    drFirstName: "Lucas",
    drLastName: "Lee",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Taper dosage as instructed",
    encounterNumber: "ENC012",
  },
  {
    chartNumber: 4,
    medicationName: "Alprazolam",
    startDate: "2024-08-01",
    endDate: "2024-08-14",
    drFirstName: "James",
    drLastName: "Thomas",
    duration: "14 days",
    dose: "0.5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take as needed for anxiety",
    encounterNumber: "ENC025",
  },
  {
    chartNumber: 4,
    medicationName: "Sertraline",
    startDate: "2024-08-04",
    endDate: "2024-08-18",
    drFirstName: "Nancy",
    drLastName: "Clark",
    duration: "14 days",
    dose: "50",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC026",
  },
  {
    chartNumber: 4,
    medicationName: "Metoprolol",
    startDate: "2024-08-08",
    endDate: "2024-08-22",
    drFirstName: "Brian",
    drLastName: "Adams",
    duration: "14 days",
    dose: "25",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC027",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    medicationName: "Warfarin",
    startDate: "2024-04-10",
    endDate: "2024-04-24",
    drFirstName: "Amelia",
    drLastName: "Hernandez",
    duration: "14 days",
    dose: "5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor INR levels",
    encounterNumber: "ENC013",
  },
  {
    chartNumber: 5,
    medicationName: "Clindamycin",
    startDate: "2024-04-12",
    endDate: "2024-04-26",
    drFirstName: "James",
    drLastName: "King",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Four times daily",
    route: "PO",
    comments: "Complete the full course",
    encounterNumber: "ENC014",
  },
  {
    chartNumber: 5,
    medicationName: "Metoprolol",
    startDate: "2024-04-14",
    endDate: "2024-04-28",
    drFirstName: "Ava",
    drLastName: "Lopez",
    duration: "14 days",
    dose: "50",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take with or without food",
    encounterNumber: "ENC015",
  },
  {
    chartNumber: 5,
    medicationName: "Duloxetine",
    startDate: "2024-08-02",
    endDate: "2024-08-16",
    drFirstName: "Angela",
    drLastName: "Baker",
    duration: "14 days",
    dose: "30",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC028",
  },
  {
    chartNumber: 5,
    medicationName: "Furosemide",
    startDate: "2024-08-05",
    endDate: "2024-08-19",
    drFirstName: "Christopher",
    drLastName: "Harris",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC029",
  },
  {
    chartNumber: 5,
    medicationName: "Prednisone",
    startDate: "2024-08-07",
    endDate: "2024-08-21",
    drFirstName: "Michelle",
    drLastName: "Walker",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC030",
  },
  {
    chartNumber: 6,
    medicationName: "Loratadine",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "Sarah",
    drLastName: "Miller",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC031",
  },
  {
    chartNumber: 6,
    medicationName: "Azithromycin",
    startDate: "2024-08-03",
    endDate: "2024-08-17",
    drFirstName: "Paul",
    drLastName: "Martinez",
    duration: "14 days",
    dose: "250",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with plenty of water",
    encounterNumber: "ENC032",
  },
  {
    chartNumber: 6,
    medicationName: "Metoprolol",
    startDate: "2024-08-05",
    endDate: "2024-08-19",
    drFirstName: "Lisa",
    drLastName: "Jackson",
    duration: "14 days",
    dose: "50",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Monitor blood pressure regularly",
    encounterNumber: "ENC033",
  },
  {
    chartNumber: 6,
    medicationName: "Ibuprofen",
    startDate: "2024-08-07",
    endDate: "2024-08-21",
    drFirstName: "Eric",
    drLastName: "Rodriguez",
    duration: "14 days",
    dose: "400",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Every 8 hours",
    route: "PO",
    comments: "Take with food to avoid stomach upset",
    encounterNumber: "ENC034",
  },
  {
    chartNumber: 6,
    medicationName: "Amlodipine",
    startDate: "2024-08-09",
    endDate: "2024-08-23",
    drFirstName: "Emily",
    drLastName: "Wilson",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor for swelling",
    encounterNumber: "ENC035",
  },
  {
    chartNumber: 6,
    medicationName: "Simvastatin",
    startDate: "2024-08-11",
    endDate: "2024-08-25",
    drFirstName: "David",
    drLastName: "White",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the evening",
    encounterNumber: "ENC036",
  },
  {
    chartNumber: 7,
    medicationName: "Citalopram",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "Anna",
    drLastName: "Harris",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC037",
  },
  {
    chartNumber: 7,
    medicationName: "Prednisone",
    startDate: "2024-08-04",
    endDate: "2024-08-18",
    drFirstName: "Mark",
    drLastName: "Davis",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC038",
  },
  {
    chartNumber: 7,
    medicationName: "Doxycycline",
    startDate: "2024-08-06",
    endDate: "2024-08-20",
    drFirstName: "Nancy",
    drLastName: "Thompson",
    duration: "14 days",
    dose: "100",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take with a full glass of water",
    encounterNumber: "ENC039",
  },
  {
    chartNumber: 7,
    medicationName: "Lisinopril",
    startDate: "2024-08-08",
    endDate: "2024-08-22",
    drFirstName: "James",
    drLastName: "Lee",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure regularly",
    encounterNumber: "ENC040",
  },
  {
    chartNumber: 7,
    medicationName: "Gabapentin",
    startDate: "2024-08-10",
    endDate: "2024-08-24",
    drFirstName: "Jennifer",
    drLastName: "Garcia",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Three times daily",
    route: "PO",
    comments: "Take with food if needed",
    encounterNumber: "ENC041",
  },
  {
    chartNumber: 7,
    medicationName: "Omeprazole",
    startDate: "2024-08-12",
    endDate: "2024-08-26",
    drFirstName: "Robert",
    drLastName: "Martinez",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take before breakfast",
    encounterNumber: "ENC042",
  },
  {
    chartNumber: 8,
    medicationName: "Alprazolam",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "Laura",
    drLastName: "Parker",
    duration: "14 days",
    dose: "1",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take as needed for anxiety",
    encounterNumber: "ENC043",
  },
  {
    chartNumber: 8,
    medicationName: "Sertraline",
    startDate: "2024-08-04",
    endDate: "2024-08-18",
    drFirstName: "George",
    drLastName: "Nelson",
    duration: "14 days",
    dose: "50",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC044",
  },
  {
    chartNumber: 8,
    medicationName: "Amlodipine",
    startDate: "2024-08-07",
    endDate: "2024-08-21",
    drFirstName: "Amy",
    drLastName: "Young",
    duration: "14 days",
    dose: "5",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC045",
  },
  {
    chartNumber: 8,
    medicationName: "Furosemide",
    startDate: "2024-08-09",
    endDate: "2024-08-23",
    drFirstName: "Brian",
    drLastName: "King",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC046",
  },
  {
    chartNumber: 8,
    medicationName: "Duloxetine",
    startDate: "2024-08-11",
    endDate: "2024-08-25",
    drFirstName: "Jessica",
    drLastName: "Wright",
    duration: "14 days",
    dose: "30",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC047",
  },
  {
    chartNumber: 8,
    medicationName: "Hydrochlorothiazide",
    startDate: "2024-08-13",
    endDate: "2024-08-27",
    drFirstName: "Michael",
    drLastName: "Green",
    duration: "14 days",
    dose: "25",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC048",
  },
  {
    chartNumber: 9,
    medicationName: "Lorazepam",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "Nancy",
    drLastName: "Johnson",
    duration: "14 days",
    dose: "1",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take as needed for anxiety",
    encounterNumber: "ENC049",
  },
  {
    chartNumber: 9,
    medicationName: "Metformin",
    startDate: "2024-08-03",
    endDate: "2024-08-17",
    drFirstName: "William",
    drLastName: "Clark",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take after meals",
    encounterNumber: "ENC050",
  },
  {
    chartNumber: 9,
    medicationName: "Amoxicillin",
    startDate: "2024-08-06",
    endDate: "2024-08-20",
    drFirstName: "Rachel",
    drLastName: "Scott",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Three times daily",
    route: "PO",
    comments: "Complete full course",
    encounterNumber: "ENC051",
  },
  {
    chartNumber: 9,
    medicationName: "Ciprofloxacin",
    startDate: "2024-08-08",
    endDate: "2024-08-22",
    drFirstName: "Andrew",
    drLastName: "Hall",
    duration: "14 days",
    dose: "500",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Twice daily",
    route: "PO",
    comments: "Take with a full glass of water",
    encounterNumber: "ENC052",
  },
  {
    chartNumber: 9,
    medicationName: "Lisinopril",
    startDate: "2024-08-10",
    endDate: "2024-08-24",
    drFirstName: "Jennifer",
    drLastName: "Adams",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Monitor blood pressure",
    encounterNumber: "ENC053",
  },
  {
    chartNumber: 9,
    medicationName: "Prednisone",
    startDate: "2024-08-12",
    endDate: "2024-08-26",
    drFirstName: "Daniel",
    drLastName: "Turner",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC054",
  },
  {
    chartNumber: 10,
    medicationName: "Hydrochlorothiazide",
    startDate: "2024-08-01",
    endDate: "2024-08-15",
    drFirstName: "Karen",
    drLastName: "Gonzalez",
    duration: "14 days",
    dose: "25",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC055",
  },
  {
    chartNumber: 10,
    medicationName: "Atorvastatin",
    startDate: "2024-08-03",
    endDate: "2024-08-17",
    drFirstName: "Matthew",
    drLastName: "Harris",
    duration: "14 days",
    dose: "40",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the evening",
    encounterNumber: "ENC056",
  },
  {
    chartNumber: 10,
    medicationName: "Gabapentin",
    startDate: "2024-08-06",
    endDate: "2024-08-20",
    drFirstName: "Rebecca",
    drLastName: "Mitchell",
    duration: "14 days",
    dose: "300",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Three times daily",
    route: "PO",
    comments: "Take with food",
    encounterNumber: "ENC057",
  },
  {
    chartNumber: 10,
    medicationName: "Loratadine",
    startDate: "2024-08-08",
    endDate: "2024-08-22",
    drFirstName: "Joshua",
    drLastName: "Walker",
    duration: "14 days",
    dose: "10",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC058",
  },
  {
    chartNumber: 10,
    medicationName: "Citalopram",
    startDate: "2024-08-10",
    endDate: "2024-08-24",
    drFirstName: "Lauren",
    drLastName: "Sullivan",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take in the morning",
    encounterNumber: "ENC059",
  },
  {
    chartNumber: 10,
    medicationName: "Omeprazole",
    startDate: "2024-08-12",
    endDate: "2024-08-26",
    drFirstName: "James",
    drLastName: "Perry",
    duration: "14 days",
    dose: "20",
    doseUnit: "mg",
    intake: "Oral",
    frequency: "Once daily",
    route: "PO",
    comments: "Take before breakfast",
    encounterNumber: "ENC060",
  },
];
