export const problemsData = [
  {
    chartNumber: 1,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 1,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 1,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 2,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 2,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 2,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 3,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 3,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 3,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 4,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 4,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 4,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 5,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 5,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
  {
    chartNumber: 5,
    diagCode: "",
    diagDesc: "",
    probDate: "",
    drFirstName: "",
    drLastName: "",
  },
];
