export const problemsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    diagCode: "I10",
    diagDesc: "Essential hypertension",
    probDate: "2024-08-01",
    drFirstName: "John",
    drLastName: "Doe",
    encounterNumber: "E001",
  },
  {
    chartNumber: 1,
    diagCode: "E11.9",
    diagDesc: "Type 2 diabetes mellitus without complications",
    probDate: "2024-08-03",
    drFirstName: "Jane",
    drLastName: "Smith",
    encounterNumber: "E002",
  },
  {
    chartNumber: 1,
    diagCode: "J45.40",
    diagDesc: "Moderate persistent asthma, uncomplicated",
    probDate: "2024-08-05",
    drFirstName: "Michael",
    drLastName: "Johnson",
    encounterNumber: "E003",
  },
  {
    chartNumber: 1,
    diagCode: "I10",
    diagDesc: "Essential hypertension",
    probDate: "2024-08-01",
    drFirstName: "John",
    drLastName: "Doe",
    encounterNumber: "E004",
  },
  {
    chartNumber: 1,
    diagCode: "E11.9",
    diagDesc: "Type 2 diabetes mellitus without complications",
    probDate: "2024-08-03",
    drFirstName: "Jane",
    drLastName: "Smith",
    encounterNumber: "E005",
  },
  {
    chartNumber: 1,
    diagCode: "J45.40",
    diagDesc: "Moderate persistent asthma, uncomplicated",
    probDate: "2024-08-05",
    drFirstName: "Michael",
    drLastName: "Johnson",
    encounterNumber: "E006",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    diagCode: "M54.5",
    diagDesc: "Low back pain",
    probDate: "2024-07-10",
    drFirstName: "Emily",
    drLastName: "Brown",
    encounterNumber: "E007",
  },
  {
    chartNumber: 2,
    diagCode: "R10.9",
    diagDesc: "Abdominal pain, unspecified",
    probDate: "2024-07-12",
    drFirstName: "David",
    drLastName: "Wilson",
    encounterNumber: "E008",
  },
  {
    chartNumber: 2,
    diagCode: "G43.909",
    diagDesc: "Migraine, unspecified, not intractable",
    probDate: "2024-07-14",
    drFirstName: "Olivia",
    drLastName: "Taylor",
    encounterNumber: "E009",
  },
  {
    chartNumber: 2,
    diagCode: "M54.5",
    diagDesc: "Low back pain",
    probDate: "2024-08-01",
    drFirstName: "Emily",
    drLastName: "Brown",
    encounterNumber: "E010",
  },
  {
    chartNumber: 2,
    diagCode: "R51",
    diagDesc: "Headache",
    probDate: "2024-08-03",
    drFirstName: "David",
    drLastName: "Wilson",
    encounterNumber: "E011",
  },
  {
    chartNumber: 2,
    diagCode: "G43.909",
    diagDesc: "Migraine, unspecified, not intractable, without aura",
    probDate: "2024-08-05",
    drFirstName: "Sarah",
    drLastName: "Miller",
    encounterNumber: "E012",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    diagCode: "F32.9",
    diagDesc: "Major depressive disorder, single episode, unspecified",
    probDate: "2024-06-15",
    drFirstName: "Christopher",
    drLastName: "Anderson",
    encounterNumber: "E013",
  },
  {
    chartNumber: 3,
    diagCode: "N40",
    diagDesc: "Benign prostatic hyperplasia",
    probDate: "2024-06-18",
    drFirstName: "Sophia",
    drLastName: "Thomas",
    encounterNumber: "E014",
  },
  {
    chartNumber: 3,
    diagCode: "K21.9",
    diagDesc: "Gastro-esophageal reflux disease without esophagitis",
    probDate: "2024-06-20",
    drFirstName: "Isabella",
    drLastName: "Martinez",
    encounterNumber: "E015",
  },
  {
    chartNumber: 3,
    diagCode: "N40.1",
    diagDesc: "Benign prostatic hyperplasia with lower urinary tract symptoms",
    probDate: "2024-08-01",
    drFirstName: "Robert",
    drLastName: "Taylor",
    encounterNumber: "E016",
  },
  {
    chartNumber: 3,
    diagCode: "J44.9",
    diagDesc: "Chronic obstructive pulmonary disease, unspecified",
    probDate: "2024-08-03",
    drFirstName: "Laura",
    drLastName: "Anderson",
    encounterNumber: "E017",
  },
  {
    chartNumber: 3,
    diagCode: "F41.9",
    diagDesc: "Anxiety disorder, unspecified",
    probDate: "2024-08-05",
    drFirstName: "James",
    drLastName: "Harris",
    encounterNumber: "E018",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    diagCode: "H52.4",
    diagDesc: "Presbyopia",
    probDate: "2024-05-10",
    drFirstName: "Liam",
    drLastName: "Garcia",
    encounterNumber: "E019",
  },
  {
    chartNumber: 4,
    diagCode: "J30.9",
    diagDesc: "Allergic rhinitis, unspecified",
    probDate: "2024-05-12",
    drFirstName: "Mia",
    drLastName: "Rodriguez",
    encounterNumber: "E020",
  },
  {
    chartNumber: 4,
    diagCode: "L40.0",
    diagDesc: "Psoriasis vulgaris",
    probDate: "2024-05-14",
    drFirstName: "Lucas",
    drLastName: "Lee",
    encounterNumber: "E021",
  },
  {
    chartNumber: 4,
    diagCode: "I63.9",
    diagDesc: "Cerebral infarction, unspecified",
    probDate: "2024-08-01",
    drFirstName: "Jennifer",
    drLastName: "Clark",
    encounterNumber: "E022",
  },
  {
    chartNumber: 4,
    diagCode: "E78.5",
    diagDesc: "Hyperlipidemia, unspecified",
    probDate: "2024-08-03",
    drFirstName: "William",
    drLastName: "Lewis",
    encounterNumber: "E023",
  },
  {
    chartNumber: 4,
    diagCode: "R07.9",
    diagDesc: "Chest pain, unspecified",
    probDate: "2024-08-05",
    drFirstName: "Emily",
    drLastName: "Young",
    encounterNumber: "E024",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    diagCode: "I25.10",
    diagDesc:
      "Atherosclerotic heart disease of native coronary artery without angina pectoris",
    probDate: "2024-04-10",
    drFirstName: "Amelia",
    drLastName: "Hernandez",
    encounterNumber: "E025",
  },
  {
    chartNumber: 5,
    diagCode: "K70.30",
    diagDesc: "Alcoholic cirrhosis of liver without ascites",
    probDate: "2024-04-12",
    drFirstName: "James",
    drLastName: "King",
    encounterNumber: "E026",
  },
  {
    chartNumber: 5,
    diagCode: "F41.9",
    diagDesc: "Anxiety disorder, unspecified",
    probDate: "2024-04-14",
    drFirstName: "Ava",
    drLastName: "Lopez",
    encounterNumber: "E027",
  },
  {
    chartNumber: 5,
    diagCode: "K21.9",
    diagDesc: "Gastro-esophageal reflux disease without esophagitis",
    probDate: "2024-08-01",
    drFirstName: "Brian",
    drLastName: "King",
    encounterNumber: "E028",
  },
  {
    chartNumber: 5,
    diagCode: "M17.9",
    diagDesc: "Osteoarthritis of knee, unspecified",
    probDate: "2024-08-03",
    drFirstName: "Nancy",
    drLastName: "Adams",
    encounterNumber: "E029",
  },
  {
    chartNumber: 5,
    diagCode: "H25.9",
    diagDesc: "Cataract, unspecified",
    probDate: "2024-08-05",
    drFirstName: "George",
    drLastName: "Walker",
    encounterNumber: "E030",
  },
  // Chart Number 6
  {
    chartNumber: 6,
    diagCode: "I10",
    diagDesc: "Essential hypertension",
    probDate: "2024-08-01",
    drFirstName: "Henry",
    drLastName: "Scott",
    encounterNumber: "E031",
  },
  {
    chartNumber: 6,
    diagCode: "E11.9",
    diagDesc: "Type 2 diabetes mellitus without complications",
    probDate: "2024-08-03",
    drFirstName: "Grace",
    drLastName: "Roberts",
    encounterNumber: "E032",
  },
  {
    chartNumber: 6,
    diagCode: "J30.9",
    diagDesc: "Allergic rhinitis, unspecified",
    probDate: "2024-08-05",
    drFirstName: "Joseph",
    drLastName: "Mitchell",
    encounterNumber: "E033",
  },
  {
    chartNumber: 6,
    diagCode: "N39.0",
    diagDesc: "Urinary tract infection, site not specified",
    probDate: "2024-08-07",
    drFirstName: "Emma",
    drLastName: "White",
    encounterNumber: "E034",
  },
  {
    chartNumber: 6,
    diagCode: "K52.9",
    diagDesc: "Noninfective gastroenteritis and colitis, unspecified",
    probDate: "2024-08-09",
    drFirstName: "Liam",
    drLastName: "Johnson",
    encounterNumber: "E035",
  },
  {
    chartNumber: 6,
    diagCode: "H40.9",
    diagDesc: "Glaucoma, unspecified",
    probDate: "2024-08-11",
    drFirstName: "Sophia",
    drLastName: "Miller",
    encounterNumber: "E036",
  },

  // Chart Number 7
  {
    chartNumber: 7,
    diagCode: "M81.0",
    diagDesc: "Age-related osteoporosis without current pathological fracture",
    probDate: "2024-08-01",
    drFirstName: "Lucas",
    drLastName: "King",
    encounterNumber: "E037",
  },
  {
    chartNumber: 7,
    diagCode: "C50.9",
    diagDesc: "Malignant neoplasm of breast, unspecified",
    probDate: "2024-08-03",
    drFirstName: "Olivia",
    drLastName: "Harris",
    encounterNumber: "E038",
  },
  {
    chartNumber: 7,
    diagCode: "F32.9",
    diagDesc: "Major depressive disorder, single episode, unspecified",
    probDate: "2024-08-05",
    drFirstName: "Ethan",
    drLastName: "Clark",
    encounterNumber: "E039",
  },
  {
    chartNumber: 7,
    diagCode: "J45.50",
    diagDesc: "Moderate persistent asthma with exacerbation",
    probDate: "2024-08-07",
    drFirstName: "Ava",
    drLastName: "Taylor",
    encounterNumber: "E040",
  },
  {
    chartNumber: 7,
    diagCode: "I63.9",
    diagDesc: "Cerebral infarction, unspecified",
    probDate: "2024-08-09",
    drFirstName: "Noah",
    drLastName: "Martinez",
    encounterNumber: "E041",
  },
  {
    chartNumber: 7,
    diagCode: "R10.9",
    diagDesc: "Abdominal pain, unspecified",
    probDate: "2024-08-11",
    drFirstName: "Mia",
    drLastName: "Roberts",
    encounterNumber: "E042",
  },

  // Chart Number 8
  {
    chartNumber: 8,
    diagCode: "I50.9",
    diagDesc: "Heart failure, unspecified",
    probDate: "2024-08-01",
    drFirstName: "Daniel",
    drLastName: "Perez",
    encounterNumber: "E043",
  },
  {
    chartNumber: 8,
    diagCode: "K21.9",
    diagDesc: "Gastro-esophageal reflux disease without esophagitis",
    probDate: "2024-08-03",
    drFirstName: "Emily",
    drLastName: "Green",
    encounterNumber: "E044",
  },
  {
    chartNumber: 8,
    diagCode: "M16.11",
    diagDesc: "Unilateral primary osteoarthritis of right hip",
    probDate: "2024-08-05",
    drFirstName: "James",
    drLastName: "Brown",
    encounterNumber: "E045",
  },
  {
    chartNumber: 8,
    diagCode: "N18.3",
    diagDesc: "Chronic kidney disease stage 3 (moderate)",
    probDate: "2024-08-07",
    drFirstName: "Isabella",
    drLastName: "Jones",
    encounterNumber: "E046",
  },
  {
    chartNumber: 8,
    diagCode: "F41.1",
    diagDesc: "Generalized anxiety disorder",
    probDate: "2024-08-09",
    drFirstName: "Alexander",
    drLastName: "Wilson",
    encounterNumber: "E047",
  },
  {
    chartNumber: 8,
    diagCode: "H35.9",
    diagDesc: "Unspecified retinal disorder",
    probDate: "2024-08-11",
    drFirstName: "Sophia",
    drLastName: "Johnson",
    encounterNumber: "E048",
  },

  // Chart Number 9
  {
    chartNumber: 9,
    diagCode: "E11.65",
    diagDesc: "Type 2 diabetes mellitus with hyperglycemia",
    probDate: "2024-08-01",
    drFirstName: "Michael",
    drLastName: "Williams",
    encounterNumber: "E049",
  },
  {
    chartNumber: 9,
    diagCode: "J44.9",
    diagDesc: "Chronic obstructive pulmonary disease, unspecified",
    probDate: "2024-08-03",
    drFirstName: "Chloe",
    drLastName: "Taylor",
    encounterNumber: "E050",
  },
  {
    chartNumber: 9,
    diagCode: "K80.00",
    diagDesc:
      "Calculus of gallbladder with acute cholecystitis, without obstruction",
    probDate: "2024-08-05",
    drFirstName: "Liam",
    drLastName: "Davis",
    encounterNumber: "E051",
  },
  {
    chartNumber: 9,
    diagCode: "M17.11",
    diagDesc: "Unilateral primary osteoarthritis of right knee",
    probDate: "2024-08-07",
    drFirstName: "Charlotte",
    drLastName: "Miller",
    encounterNumber: "E052",
  },
  {
    chartNumber: 9,
    diagCode: "N40.1",
    diagDesc: "Benign prostatic hyperplasia with lower urinary tract symptoms",
    probDate: "2024-08-09",
    drFirstName: "Benjamin",
    drLastName: "Garcia",
    encounterNumber: "E053",
  },
  {
    chartNumber: 9,
    diagCode: "R07.9",
    diagDesc: "Chest pain, unspecified",
    probDate: "2024-08-11",
    drFirstName: "Avery",
    drLastName: "Rodriguez",
    encounterNumber: "E054",
  },

  // Chart Number 10
  {
    chartNumber: 10,
    diagCode: "I50.9",
    diagDesc: "Heart failure, unspecified",
    probDate: "2024-08-01",
    drFirstName: "Daniel",
    drLastName: "Parker",
    encounterNumber: "E055",
  },
  {
    chartNumber: 10,
    diagCode: "K21.9",
    diagDesc: "Gastro-esophageal reflux disease without esophagitis",
    probDate: "2024-08-03",
    drFirstName: "Mia",
    drLastName: "Lee",
    encounterNumber: "E056",
  },
  {
    chartNumber: 10,
    diagCode: "M16.11",
    diagDesc: "Unilateral primary osteoarthritis of right hip",
    probDate: "2024-08-05",
    drFirstName: "Ethan",
    drLastName: "Young",
    encounterNumber: "E057",
  },
  {
    chartNumber: 10,
    diagCode: "N18.3",
    diagDesc: "Chronic kidney disease stage 3 (moderate)",
    probDate: "2024-08-07",
    drFirstName: "Olivia",
    drLastName: "Martin",
    encounterNumber: "E058",
  },
  {
    chartNumber: 10,
    diagCode: "F41.1",
    diagDesc: "Generalized anxiety disorder",
    probDate: "2024-08-09",
    drFirstName: "William",
    drLastName: "Hernandez",
    encounterNumber: "E059",
  },
  {
    chartNumber: 10,
    diagCode: "H35.9",
    diagDesc: "Unspecified retinal disorder",
    probDate: "2024-08-11",
    drFirstName: "Emily",
    drLastName: "Nelson",
    encounterNumber: "E060",
  },
];
