export const proceduresData = [
  // Chart Number 1
  {
    chartNumber: 1,
    encounterNumber: "E123",
    facilityName: "General Hospital",
    testName: "Complete Blood Count",
    testDate: "2024-08-01",
    result1: "Normal",
    result2: "Normal",
    result3: "Normal",
    result4: "Normal",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 1,
    encounterNumber: "E124",
    facilityName: "Health Clinic",
    testName: "Urinalysis",
    testDate: "2024-08-03",
    result1: "Normal",
    result2: "Normal",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 1,
    encounterNumber: "E125",
    facilityName: "Specialty Lab",
    testName: "Lipid Panel",
    testDate: "2024-08-05",
    result1: "Cholesterol: Normal",
    result2: "Triglycerides: Normal",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-06",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    encounterNumber: "E223",
    facilityName: "Urgent Care",
    testName: "Chest X-Ray",
    testDate: "2024-07-10",
    result1: "Clear",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-07-11",
  },
  {
    chartNumber: 2,
    encounterNumber: "E224",
    facilityName: "Diagnostic Imaging",
    testName: "MRI Brain",
    testDate: "2024-07-12",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-07-13",
  },
  {
    chartNumber: 2,
    encounterNumber: "E225",
    facilityName: "Health Center",
    testName: "Echocardiogram",
    testDate: "2024-07-14",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-07-15",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    encounterNumber: "E323",
    facilityName: "Laboratory Services",
    testName: "Glucose Test",
    testDate: "2024-06-15",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-06-16",
  },
  {
    chartNumber: 3,
    encounterNumber: "E324",
    facilityName: "Medical Labs",
    testName: "Thyroid Function Test",
    testDate: "2024-06-17",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-06-18",
  },
  {
    chartNumber: 3,
    encounterNumber: "E325",
    facilityName: "Clinical Lab",
    testName: "Vitamin D Levels",
    testDate: "2024-06-19",
    result1: "Low",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-06-20",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    encounterNumber: "E423",
    facilityName: "Advanced Diagnostics",
    testName: "Hematology Panel",
    testDate: "2024-05-10",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-05-11",
  },
  {
    chartNumber: 4,
    encounterNumber: "E424",
    facilityName: "Heart Center",
    testName: "Stress Test",
    testDate: "2024-05-12",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-05-13",
  },
  {
    chartNumber: 4,
    encounterNumber: "E425",
    facilityName: "Diagnostic Center",
    testName: "Allergy Test",
    testDate: "2024-05-14",
    result1: "Positive",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-05-15",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    encounterNumber: "E523",
    facilityName: "Health Institute",
    testName: "Liver Function Test",
    testDate: "2024-04-10",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-04-11",
  },
  {
    chartNumber: 5,
    encounterNumber: "E524",
    facilityName: "Wellness Clinic",
    testName: "Bone Density Test",
    testDate: "2024-04-12",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-04-13",
  },
  {
    chartNumber: 5,
    encounterNumber: "E525",
    facilityName: "Diagnostic Labs",
    testName: "Hepatitis Panel",
    testDate: "2024-04-14",
    result1: "Negative",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-04-15",
  },
];
