export const proceduresData = [
  // Chart Number 1
  {
    chartNumber: 1,
    encounterNumber: "E123",
    facilityName: "General Hospital",
    testName: "Complete Blood Count",
    testDate: "2024-08-01",
    result1: "Normal",
    result2: "Normal",
    result3: "Normal",
    result4: "Normal",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 1,
    encounterNumber: "E124",
    facilityName: "Health Clinic",
    testName: "Urinalysis",
    testDate: "2024-08-03",
    result1: "Normal",
    result2: "Normal",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 1,
    encounterNumber: "E125",
    facilityName: "Specialty Lab",
    testName: "Lipid Panel",
    testDate: "2024-08-05",
    result1: "Cholesterol: Normal",
    result2: "Triglycerides: Normal",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 1,
    encounterNumber: "ENC016",
    facilityName: "General Hospital",
    testName: "Complete Blood Count",
    testDate: "2024-08-01",
    result1: "WBC: 6.1",
    result2: "RBC: 4.7",
    result3: "Hemoglobin: 13.5",
    result4: "Hematocrit: 40.2",
    result5: "Platelets: 220",
    result6: "MCV: 85",
    result7: "MCH: 29",
    result8: "MCHC: 34",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 1,
    encounterNumber: "ENC017",
    facilityName: "Health Clinic",
    testName: "Urinalysis",
    testDate: "2024-08-03",
    result1: "Appearance: Clear",
    result2: "Color: Yellow",
    result3: "Specific Gravity: 1.015",
    result4: "pH: 6.0",
    result5: "Glucose: Negative",
    result6: "Protein: Negative",
    result7: "Leukocytes: Negative",
    result8: "Nitrites: Negative",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 1,
    encounterNumber: "ENC018",
    facilityName: "Specialty Lab",
    testName: "Lipid Panel",
    testDate: "2024-08-05",
    result1: "Total Cholesterol: 190",
    result2: "HDL: 55",
    result3: "LDL: 120",
    result4: "Triglycerides: 130",
    result5: "VLDL: 15",
    result6: "Non-HDL: 135",
    result7: "Chol/HDL Ratio: 3.5",
    result8: "Glucose: 90",
    resultDate: "2024-08-06",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    encounterNumber: "E223",
    facilityName: "Urgent Care",
    testName: "Chest X-Ray",
    testDate: "2024-07-10",
    result1: "Clear",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-07-11",
  },
  {
    chartNumber: 2,
    encounterNumber: "E224",
    facilityName: "Diagnostic Imaging",
    testName: "MRI Brain",
    testDate: "2024-07-12",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-07-13",
  },
  {
    chartNumber: 2,
    encounterNumber: "E225",
    facilityName: "Health Center",
    testName: "Echocardiogram",
    testDate: "2024-07-14",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-07-15",
  },
  {
    chartNumber: 2,
    encounterNumber: "ENC019",
    facilityName: "City Hospital",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-07",
    result1: "Sodium: 140",
    result2: "Potassium: 4.2",
    result3: "Chloride: 102",
    result4: "CO2: 24",
    result5: "BUN: 18",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 92",
    result8: "Calcium: 9.5",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 2,
    encounterNumber: "ENC020",
    facilityName: "Wellness Center",
    testName: "Thyroid Function Test",
    testDate: "2024-08-09",
    result1: "TSH: 2.5",
    result2: "Free T4: 1.2",
    result3: "Free T3: 3.1",
    result4: "Total T4: 8.0",
    result5: "Total T3: 120",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 2.5",
    result8: "T3 Uptake: 33%",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 2,
    encounterNumber: "ENC021",
    facilityName: "Diagnostic Lab",
    testName: "Hemoglobin A1c",
    testDate: "2024-08-11",
    result1: "Hemoglobin A1c: 6.1%",
    result2: "Estimated Average Glucose: 126 mg/dL",
    result3: "Fasting Glucose: 90 mg/dL",
    result4: "Postprandial Glucose: 130 mg/dL",
    result5: "Insulin Level: 8",
    result6: "C-Peptide: 3.2",
    result7: "Fructosamine: 250",
    result8: "HgbA1c: 6.1%",
    resultDate: "2024-08-12",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    encounterNumber: "E323",
    facilityName: "Laboratory Services",
    testName: "Glucose Test",
    testDate: "2024-06-15",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-06-16",
  },
  {
    chartNumber: 3,
    encounterNumber: "E324",
    facilityName: "Medical Labs",
    testName: "Thyroid Function Test",
    testDate: "2024-06-17",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-06-18",
  },
  {
    chartNumber: 3,
    encounterNumber: "E325",
    facilityName: "Clinical Lab",
    testName: "Vitamin D Levels",
    testDate: "2024-06-19",
    result1: "Low",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-06-20",
  },
  {
    chartNumber: 3,
    encounterNumber: "ENC022",
    facilityName: "Premier Health",
    testName: "Comprehensive Metabolic Panel",
    testDate: "2024-08-13",
    result1: "Glucose: 95",
    result2: "Calcium: 9.8",
    result3: "Sodium: 141",
    result4: "Potassium: 4.1",
    result5: "Chloride: 104",
    result6: "CO2: 25",
    result7: "BUN: 16",
    result8: "Creatinine: 1.2",
    resultDate: "2024-08-14",
  },
  {
    chartNumber: 3,
    encounterNumber: "ENC023",
    facilityName: "Advanced Diagnostics",
    testName: "Vitamin D Test",
    testDate: "2024-08-15",
    result1: "Vitamin D (25-OH): 30 ng/mL",
    result2: "Vitamin D2: 10 ng/mL",
    result3: "Vitamin D3: 20 ng/mL",
    result4: "Parathyroid Hormone: 45 pg/mL",
    result5: "Calcium: 9.6 mg/dL",
    result6: "Phosphorus: 3.2 mg/dL",
    result7: "Magnesium: 2.1 mg/dL",
    result8: "Albumin: 4.1 g/dL",
    resultDate: "2024-08-16",
  },
  {
    chartNumber: 3,
    encounterNumber: "ENC024",
    facilityName: "Community Lab",
    testName: "Prostate-Specific Antigen (PSA)",
    testDate: "2024-08-17",
    result1: "PSA Level: 2.5 ng/mL",
    result2: "Free PSA: 0.9 ng/mL",
    result3: "Total PSA: 2.5 ng/mL",
    result4: "PSA Density: 0.1",
    result5: "PSA Velocity: 0.05",
    result6: "Prostate Volume: 30 mL",
    result7: "Bioavailable PSA: 1.2 ng/mL",
    result8: "PSA Ratio: 0.3",
    resultDate: "2024-08-18",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    encounterNumber: "E423",
    facilityName: "Advanced Diagnostics",
    testName: "Hematology Panel",
    testDate: "2024-05-10",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-05-11",
  },
  {
    chartNumber: 4,
    encounterNumber: "E424",
    facilityName: "Heart Center",
    testName: "Stress Test",
    testDate: "2024-05-12",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-05-13",
  },
  {
    chartNumber: 4,
    encounterNumber: "E425",
    facilityName: "Diagnostic Center",
    testName: "Allergy Test",
    testDate: "2024-05-14",
    result1: "Positive",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-05-15",
  },
  {
    chartNumber: 4,
    encounterNumber: "ENC025",
    facilityName: "Metro Health",
    testName: "Complete Blood Count",
    testDate: "2024-08-19",
    result1: "WBC: 6.5",
    result2: "RBC: 4.8",
    result3: "Hemoglobin: 14.0",
    result4: "Hematocrit: 41.0",
    result5: "Platelets: 230",
    result6: "MCV: 86",
    result7: "MCH: 30",
    result8: "MCHC: 35",
    resultDate: "2024-08-20",
  },
  {
    chartNumber: 4,
    encounterNumber: "ENC026",
    facilityName: "City Clinic",
    testName: "Thyroid Panel",
    testDate: "2024-08-21",
    result1: "TSH: 3.0",
    result2: "Free T4: 1.0",
    result3: "Free T3: 2.9",
    result4: "Total T4: 7.5",
    result5: "Total T3: 110",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 3.0",
    result8: "T3 Uptake: 32%",
    resultDate: "2024-08-22",
  },
  {
    chartNumber: 4,
    encounterNumber: "ENC027",
    facilityName: "Diagnostic Center",
    testName: "Lipid Profile",
    testDate: "2024-08-23",
    result1: "Total Cholesterol: 200",
    result2: "HDL: 60",
    result3: "LDL: 130",
    result4: "Triglycerides: 140",
    result5: "VLDL: 20",
    result6: "Non-HDL: 140",
    result7: "Chol/HDL Ratio: 3.3",
    result8: "Glucose: 85",
    resultDate: "2024-08-24",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    encounterNumber: "E523",
    facilityName: "Health Institute",
    testName: "Liver Function Test",
    testDate: "2024-04-10",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-04-11",
  },
  {
    chartNumber: 5,
    encounterNumber: "E524",
    facilityName: "Wellness Clinic",
    testName: "Bone Density Test",
    testDate: "2024-04-12",
    result1: "Normal",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-04-13",
  },
  {
    chartNumber: 5,
    encounterNumber: "E525",
    facilityName: "Diagnostic Labs",
    testName: "Hepatitis Panel",
    testDate: "2024-04-14",
    result1: "Negative",
    result2: "",
    result3: "",
    result4: "",
    result5: "",
    result6: "",
    result7: "",
    result8: "",
    resultDate: "2024-04-15",
  },
  {
    chartNumber: 5,
    encounterNumber: "ENC028",
    facilityName: "Elite Health",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-25",
    result1: "Sodium: 139",
    result2: "Potassium: 4.3",
    result3: "Chloride: 103",
    result4: "CO2: 22",
    result5: "BUN: 17",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 88",
    result8: "Calcium: 9.4",
    resultDate: "2024-08-26",
  },
  {
    chartNumber: 5,
    encounterNumber: "ENC029",
    facilityName: "Advanced Care",
    testName: "Vitamin B12 Test",
    testDate: "2024-08-27",
    result1: "Vitamin B12: 450 pg/mL",
    result2: "Methylmalonic Acid: 0.5",
    result3: "Homocysteine: 8.0",
    result4: "Folate: 10",
    result5: "Serum Folate: 6.0",
    result6: "Serum B12: 450",
    result7: "Red Cell Folate: 250",
    result8: "Total B12: 450",
    resultDate: "2024-08-28",
  },
  {
    chartNumber: 5,
    encounterNumber: "ENC030",
    facilityName: "Family Clinic",
    testName: "Hemoglobin A1c",
    testDate: "2024-08-29",
    result1: "Hemoglobin A1c: 6.0%",
    result2: "Estimated Average Glucose: 120 mg/dL",
    result3: "Fasting Glucose: 85 mg/dL",
    result4: "Postprandial Glucose: 125 mg/dL",
    result5: "Insulin Level: 7",
    result6: "C-Peptide: 3.0",
    result7: "Fructosamine: 230",
    result8: "HgbA1c: 6.0%",
    resultDate: "2024-08-30",
  },
  // Chart Number 6
  {
    chartNumber: 6,
    encounterNumber: "ENC031",
    facilityName: "Metro Medical",
    testName: "Complete Blood Count",
    testDate: "2024-08-01",
    result1: "WBC: 6.0",
    result2: "RBC: 4.5",
    result3: "Hemoglobin: 13.2",
    result4: "Hematocrit: 39.0",
    result5: "Platelets: 210",
    result6: "MCV: 87",
    result7: "MCH: 28",
    result8: "MCHC: 33",
    resultDate: "2024-08-02",
  },
  {
    chartNumber: 6,
    encounterNumber: "ENC032",
    facilityName: "Westside Lab",
    testName: "Urinalysis",
    testDate: "2024-08-03",
    result1: "Appearance: Clear",
    result2: "Color: Light yellow",
    result3: "Specific Gravity: 1.020",
    result4: "pH: 6.5",
    result5: "Glucose: Negative",
    result6: "Protein: Negative",
    result7: "Leukocytes: Negative",
    result8: "Nitrites: Negative",
    resultDate: "2024-08-04",
  },
  {
    chartNumber: 6,
    encounterNumber: "ENC033",
    facilityName: "Central Health",
    testName: "Lipid Panel",
    testDate: "2024-08-05",
    result1: "Total Cholesterol: 180",
    result2: "HDL: 50",
    result3: "LDL: 110",
    result4: "Triglycerides: 140",
    result5: "VLDL: 20",
    result6: "Non-HDL: 130",
    result7: "Chol/HDL Ratio: 3.6",
    result8: "Glucose: 85",
    resultDate: "2024-08-06",
  },
  {
    chartNumber: 6,
    encounterNumber: "ENC034",
    facilityName: "Northside Clinic",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-07",
    result1: "Sodium: 138",
    result2: "Potassium: 4.0",
    result3: "Chloride: 101",
    result4: "CO2: 23",
    result5: "BUN: 17",
    result6: "Creatinine: 1.0",
    result7: "Glucose: 90",
    result8: "Calcium: 9.7",
    resultDate: "2024-08-08",
  },
  {
    chartNumber: 6,
    encounterNumber: "ENC035",
    facilityName: "HealthPlus Lab",
    testName: "Thyroid Function Test",
    testDate: "2024-08-09",
    result1: "TSH: 2.3",
    result2: "Free T4: 1.1",
    result3: "Free T3: 3.0",
    result4: "Total T4: 7.8",
    result5: "Total T3: 115",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 2.8",
    result8: "T3 Uptake: 34%",
    resultDate: "2024-08-10",
  },
  {
    chartNumber: 6,
    encounterNumber: "ENC036",
    facilityName: "City Health Center",
    testName: "Vitamin D Test",
    testDate: "2024-08-11",
    result1: "Vitamin D (25-OH): 32 ng/mL",
    result2: "Vitamin D2: 11 ng/mL",
    result3: "Vitamin D3: 21 ng/mL",
    result4: "Parathyroid Hormone: 44 pg/mL",
    result5: "Calcium: 9.7 mg/dL",
    result6: "Phosphorus: 3.1 mg/dL",
    result7: "Magnesium: 2.0 mg/dL",
    result8: "Albumin: 4.2 g/dL",
    resultDate: "2024-08-12",
  },
  {
    chartNumber: 6,
    encounterNumber: "ENC037",
    facilityName: "Advanced Diagnostics",
    testName: "Prostate-Specific Antigen (PSA)",
    testDate: "2024-08-13",
    result1: "PSA Level: 2.2 ng/mL",
    result2: "Free PSA: 0.8 ng/mL",
    result3: "Total PSA: 2.2 ng/mL",
    result4: "PSA Density: 0.09",
    result5: "PSA Velocity: 0.04",
    result6: "Prostate Volume: 28 mL",
    result7: "Bioavailable PSA: 1.1 ng/mL",
    result8: "PSA Ratio: 0.36",
    resultDate: "2024-08-14",
  },

  // Chart Number 7
  {
    chartNumber: 7,
    encounterNumber: "ENC038",
    facilityName: "Bright Future Health",
    testName: "Complete Blood Count",
    testDate: "2024-08-15",
    result1: "WBC: 6.3",
    result2: "RBC: 4.6",
    result3: "Hemoglobin: 13.4",
    result4: "Hematocrit: 39.5",
    result5: "Platelets: 215",
    result6: "MCV: 88",
    result7: "MCH: 29",
    result8: "MCHC: 34",
    resultDate: "2024-08-16",
  },
  {
    chartNumber: 7,
    encounterNumber: "ENC039",
    facilityName: "Eastside Lab",
    testName: "Urinalysis",
    testDate: "2024-08-17",
    result1: "Appearance: Clear",
    result2: "Color: Yellow",
    result3: "Specific Gravity: 1.018",
    result4: "pH: 6.2",
    result5: "Glucose: Negative",
    result6: "Protein: Negative",
    result7: "Leukocytes: Negative",
    result8: "Nitrites: Negative",
    resultDate: "2024-08-18",
  },
  {
    chartNumber: 7,
    encounterNumber: "ENC040",
    facilityName: "Wellness Labs",
    testName: "Lipid Panel",
    testDate: "2024-08-19",
    result1: "Total Cholesterol: 190",
    result2: "HDL: 52",
    result3: "LDL: 115",
    result4: "Triglycerides: 135",
    result5: "VLDL: 18",
    result6: "Non-HDL: 138",
    result7: "Chol/HDL Ratio: 3.65",
    result8: "Glucose: 89",
    resultDate: "2024-08-20",
  },
  {
    chartNumber: 7,
    encounterNumber: "ENC041",
    facilityName: "Family Health Center",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-21",
    result1: "Sodium: 140",
    result2: "Potassium: 4.2",
    result3: "Chloride: 102",
    result4: "CO2: 24",
    result5: "BUN: 16",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 92",
    result8: "Calcium: 9.6",
    resultDate: "2024-08-22",
  },
  {
    chartNumber: 7,
    encounterNumber: "ENC042",
    facilityName: "Health Center",
    testName: "Thyroid Function Test",
    testDate: "2024-08-23",
    result1: "TSH: 2.1",
    result2: "Free T4: 1.2",
    result3: "Free T3: 3.2",
    result4: "Total T4: 8.1",
    result5: "Total T3: 118",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 2.9",
    result8: "T3 Uptake: 33%",
    resultDate: "2024-08-24",
  },
  {
    chartNumber: 7,
    encounterNumber: "ENC043",
    facilityName: "City Lab",
    testName: "Vitamin D Test",
    testDate: "2024-08-25",
    result1: "Vitamin D (25-OH): 34 ng/mL",
    result2: "Vitamin D2: 12 ng/mL",
    result3: "Vitamin D3: 22 ng/mL",
    result4: "Parathyroid Hormone: 42 pg/mL",
    result5: "Calcium: 9.8 mg/dL",
    result6: "Phosphorus: 3.2 mg/dL",
    result7: "Magnesium: 2.1 mg/dL",
    result8: "Albumin: 4.3 g/dL",
    resultDate: "2024-08-26",
  },

  // Chart Number 8
  {
    chartNumber: 8,
    encounterNumber: "ENC044",
    facilityName: "Regional Medical Center",
    testName: "Complete Blood Count",
    testDate: "2024-08-26",
    result1: "WBC: 6.2",
    result2: "RBC: 4.7",
    result3: "Hemoglobin: 13.5",
    result4: "Hematocrit: 39.6",
    result5: "Platelets: 220",
    result6: "MCV: 89",
    result7: "MCH: 28.5",
    result8: "MCHC: 33.5",
    resultDate: "2024-08-27",
  },
  {
    chartNumber: 8,
    encounterNumber: "ENC045",
    facilityName: "North End Lab",
    testName: "Urinalysis",
    testDate: "2024-08-27",
    result1: "Appearance: Clear",
    result2: "Color: Pale yellow",
    result3: "Specific Gravity: 1.015",
    result4: "pH: 6.4",
    result5: "Glucose: Negative",
    result6: "Protein: Trace",
    result7: "Leukocytes: Negative",
    result8: "Nitrites: Negative",
    resultDate: "2024-08-28",
  },
  {
    chartNumber: 8,
    encounterNumber: "ENC046",
    facilityName: "Southside Health",
    testName: "Lipid Panel",
    testDate: "2024-08-28",
    result1: "Total Cholesterol: 200",
    result2: "HDL: 55",
    result3: "LDL: 120",
    result4: "Triglycerides: 145",
    result5: "VLDL: 22",
    result6: "Non-HDL: 145",
    result7: "Chol/HDL Ratio: 3.63",
    result8: "Glucose: 92",
    resultDate: "2024-08-29",
  },
  {
    chartNumber: 8,
    encounterNumber: "ENC047",
    facilityName: "Downtown Clinic",
    testName: "Basic Metabolic Panel",
    testDate: "2024-08-29",
    result1: "Sodium: 139",
    result2: "Potassium: 4.1",
    result3: "Chloride: 104",
    result4: "CO2: 23",
    result5: "BUN: 15",
    result6: "Creatinine: 1.2",
    result7: "Glucose: 95",
    result8: "Calcium: 9.5",
    resultDate: "2024-08-30",
  },
  {
    chartNumber: 8,
    encounterNumber: "ENC048",
    facilityName: "Health Alliance",
    testName: "Thyroid Function Test",
    testDate: "2024-08-31",
    result1: "TSH: 2.2",
    result2: "Free T4: 1.0",
    result3: "Free T3: 3.1",
    result4: "Total T4: 8.0",
    result5: "Total T3: 116",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 3.0",
    result8: "T3 Uptake: 32%",
    resultDate: "2024-09-01",
  },
  {
    chartNumber: 8,
    encounterNumber: "ENC049",
    facilityName: "Wellness Lab",
    testName: "Vitamin D Test",
    testDate: "2024-09-02",
    result1: "Vitamin D (25-OH): 31 ng/mL",
    result2: "Vitamin D2: 10 ng/mL",
    result3: "Vitamin D3: 21 ng/mL",
    result4: "Parathyroid Hormone: 46 pg/mL",
    result5: "Calcium: 9.6 mg/dL",
    result6: "Phosphorus: 3.3 mg/dL",
    result7: "Magnesium: 2.2 mg/dL",
    result8: "Albumin: 4.1 g/dL",
    resultDate: "2024-09-03",
  },

  // Chart Number 9
  {
    chartNumber: 9,
    encounterNumber: "ENC050",
    facilityName: "Elite Health",
    testName: "Complete Blood Count",
    testDate: "2024-09-04",
    result1: "WBC: 6.1",
    result2: "RBC: 4.6",
    result3: "Hemoglobin: 13.3",
    result4: "Hematocrit: 39.2",
    result5: "Platelets: 212",
    result6: "MCV: 88",
    result7: "MCH: 29",
    result8: "MCHC: 33",
    resultDate: "2024-09-05",
  },
  {
    chartNumber: 9,
    encounterNumber: "ENC051",
    facilityName: "Advanced Lab",
    testName: "Urinalysis",
    testDate: "2024-09-06",
    result1: "Appearance: Clear",
    result2: "Color: Yellow",
    result3: "Specific Gravity: 1.022",
    result4: "pH: 6.6",
    result5: "Glucose: Negative",
    result6: "Protein: Negative",
    result7: "Leukocytes: Negative",
    result8: "Nitrites: Negative",
    resultDate: "2024-09-07",
  },
  {
    chartNumber: 9,
    encounterNumber: "ENC052",
    facilityName: "City Health",
    testName: "Lipid Panel",
    testDate: "2024-09-08",
    result1: "Total Cholesterol: 185",
    result2: "HDL: 53",
    result3: "LDL: 118",
    result4: "Triglycerides: 130",
    result5: "VLDL: 24",
    result6: "Non-HDL: 132",
    result7: "Chol/HDL Ratio: 3.48",
    result8: "Glucose: 90",
    resultDate: "2024-09-09",
  },
  {
    chartNumber: 9,
    encounterNumber: "ENC053",
    facilityName: "Health Center",
    testName: "Basic Metabolic Panel",
    testDate: "2024-09-10",
    result1: "Sodium: 137",
    result2: "Potassium: 4.0",
    result3: "Chloride: 100",
    result4: "CO2: 22",
    result5: "BUN: 16",
    result6: "Creatinine: 1.1",
    result7: "Glucose: 93",
    result8: "Calcium: 9.4",
    resultDate: "2024-09-11",
  },
  {
    chartNumber: 9,
    encounterNumber: "ENC054",
    facilityName: "Northside Lab",
    testName: "Thyroid Function Test",
    testDate: "2024-09-12",
    result1: "TSH: 2.4",
    result2: "Free T4: 1.2",
    result3: "Free T3: 3.3",
    result4: "Total T4: 8.3",
    result5: "Total T3: 120",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 2.7",
    result8: "T3 Uptake: 31%",
    resultDate: "2024-09-13",
  },
  {
    chartNumber: 9,
    encounterNumber: "ENC055",
    facilityName: "Westside Health",
    testName: "Vitamin D Test",
    testDate: "2024-09-14",
    result1: "Vitamin D (25-OH): 33 ng/mL",
    result2: "Vitamin D2: 11 ng/mL",
    result3: "Vitamin D3: 22 ng/mL",
    result4: "Parathyroid Hormone: 44 pg/mL",
    result5: "Calcium: 9.7 mg/dL",
    result6: "Phosphorus: 3.4 mg/dL",
    result7: "Magnesium: 2.3 mg/dL",
    result8: "Albumin: 4.2 g/dL",
    resultDate: "2024-09-15",
  },

  // Chart Number 10
  {
    chartNumber: 10,
    encounterNumber: "ENC056",
    facilityName: "Regional Lab",
    testName: "Complete Blood Count",
    testDate: "2024-09-16",
    result1: "WBC: 6.0",
    result2: "RBC: 4.5",
    result3: "Hemoglobin: 13.2",
    result4: "Hematocrit: 38.8",
    result5: "Platelets: 210",
    result6: "MCV: 87",
    result7: "MCH: 28.7",
    result8: "MCHC: 32.9",
    resultDate: "2024-09-17",
  },
  {
    chartNumber: 10,
    encounterNumber: "ENC057",
    facilityName: "Central Health",
    testName: "Urinalysis",
    testDate: "2024-09-18",
    result1: "Appearance: Clear",
    result2: "Color: Pale yellow",
    result3: "Specific Gravity: 1.018",
    result4: "pH: 6.5",
    result5: "Glucose: Negative",
    result6: "Protein: Negative",
    result7: "Leukocytes: Negative",
    result8: "Nitrites: Negative",
    resultDate: "2024-09-19",
  },
  {
    chartNumber: 10,
    encounterNumber: "ENC058",
    facilityName: "Eastside Lab",
    testName: "Lipid Panel",
    testDate: "2024-09-20",
    result1: "Total Cholesterol: 190",
    result2: "HDL: 52",
    result3: "LDL: 115",
    result4: "Triglycerides: 140",
    result5: "VLDL: 28",
    result6: "Non-HDL: 138",
    result7: "Chol/HDL Ratio: 3.65",
    result8: "Glucose: 94",
    resultDate: "2024-09-21",
  },
  {
    chartNumber: 10,
    encounterNumber: "ENC059",
    facilityName: "City Health",
    testName: "Basic Metabolic Panel",
    testDate: "2024-09-22",
    result1: "Sodium: 138",
    result2: "Potassium: 4.2",
    result3: "Chloride: 102",
    result4: "CO2: 24",
    result5: "BUN: 14",
    result6: "Creatinine: 1.3",
    result7: "Glucose: 97",
    result8: "Calcium: 9.6",
    resultDate: "2024-09-23",
  },
  {
    chartNumber: 10,
    encounterNumber: "ENC060",
    facilityName: "North End Lab",
    testName: "Thyroid Function Test",
    testDate: "2024-09-24",
    result1: "TSH: 2.3",
    result2: "Free T4: 1.1",
    result3: "Free T3: 3.2",
    result4: "Total T4: 8.1",
    result5: "Total T3: 118",
    result6: "Thyroid Antibodies: Negative",
    result7: "Thyroglobulin: 3.2",
    result8: "T3 Uptake: 33%",
    resultDate: "2024-09-25",
  },
  {
    chartNumber: 10,
    encounterNumber: "ENC061",
    facilityName: "Westside Health",
    testName: "Vitamin D Test",
    testDate: "2024-09-26",
    result1: "Vitamin D (25-OH): 32 ng/mL",
    result2: "Vitamin D2: 9 ng/mL",
    result3: "Vitamin D3: 23 ng/mL",
    result4: "Parathyroid Hormone: 45 pg/mL",
    result5: "Calcium: 9.8 mg/dL",
    result6: "Phosphorus: 3.5 mg/dL",
    result7: "Magnesium: 2.4 mg/dL",
    result8: "Albumin: 4.0 g/dL",
    resultDate: "2024-09-27",
  },
];
