export const visitsDate = [
  // Chart Number 1
  {
    chartNumber: 1,
    encounterNumber: "E001",
    visitDate: "2024-08-01",
    drFirstName: "Alice",
    drLastName: "Smith",
    visitType: "Routine Check-up",
    PDFFile: "report_001.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E002",
    visitDate: "2024-08-05",
    drFirstName: "Bob",
    drLastName: "Johnson",
    visitType: "Consultation",
    PDFFile: "report_002.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E003",
    visitDate: "2024-08-10",
    drFirstName: "Carol",
    drLastName: "Williams",
    visitType: "Follow-up",
    PDFFile: "report_003.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    encounterNumber: "E004",
    visitDate: "2024-07-15",
    drFirstName: "David",
    drLastName: "Brown",
    visitType: "Emergency",
    PDFFile: "report_004.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E005",
    visitDate: "2024-07-20",
    drFirstName: "Eve",
    drLastName: "Jones",
    visitType: "Routine Check-up",
    PDFFile: "report_005.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E006",
    visitDate: "2024-07-25",
    drFirstName: "Frank",
    drLastName: "Miller",
    visitType: "Consultation",
    PDFFile: "report_006.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    encounterNumber: "E007",
    visitDate: "2024-06-30",
    drFirstName: "Grace",
    drLastName: "Davis",
    visitType: "Follow-up",
    PDFFile: "report_007.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E008",
    visitDate: "2024-07-05",
    drFirstName: "Henry",
    drLastName: "Wilson",
    visitType: "Emergency",
    PDFFile: "report_008.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E009",
    visitDate: "2024-07-10",
    drFirstName: "Ivy",
    drLastName: "Moore",
    visitType: "Routine Check-up",
    PDFFile: "report_009.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    encounterNumber: "E010",
    visitDate: "2024-06-01",
    drFirstName: "Jack",
    drLastName: "Taylor",
    visitType: "Consultation",
    PDFFile: "report_010.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E011",
    visitDate: "2024-06-05",
    drFirstName: "Kathy",
    drLastName: "Anderson",
    visitType: "Follow-up",
    PDFFile: "report_011.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E012",
    visitDate: "2024-06-10",
    drFirstName: "Leo",
    drLastName: "Thomas",
    visitType: "Emergency",
    PDFFile: "report_012.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    encounterNumber: "E013",
    visitDate: "2024-05-15",
    drFirstName: "Mia",
    drLastName: "Jackson",
    visitType: "Routine Check-up",
    PDFFile: "report_013.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E014",
    visitDate: "2024-05-20",
    drFirstName: "Nate",
    drLastName: "White",
    visitType: "Consultation",
    PDFFile: "report_014.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E015",
    visitDate: "2024-05-25",
    drFirstName: "Olivia",
    drLastName: "Harris",
    visitType: "Follow-up",
    PDFFile: "report_015.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
];
