export const visitsData = [
  // Chart Number 1
  {
    chartNumber: 1,
    encounterNumber: "E001",
    visitDate: "2024-08-01",
    drFirstName: "Alice",
    drLastName: "Smith",
    visitType: "Routine Check-up",
    PDFFile: "report_001.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E002",
    visitDate: "2024-08-05",
    drFirstName: "Bob",
    drLastName: "Johnson",
    visitType: "Consultation",
    PDFFile: "report_002.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E003",
    visitDate: "2024-08-10",
    drFirstName: "Carol",
    drLastName: "Williams",
    visitType: "Follow-up",
    PDFFile: "report_003.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E004",
    visitDate: "2024-08-02",
    drFirstName: "John",
    drLastName: "Doe",
    visitType: "Initial Consultation",
    PDFFile: "report_016.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E005",
    visitDate: "2024-08-06",
    drFirstName: "Emily",
    drLastName: "Davis",
    visitType: "Routine Check-up",
    PDFFile: "report_017.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 1,
    encounterNumber: "E006",
    visitDate: "2024-08-12",
    drFirstName: "Michael",
    drLastName: "Brown",
    visitType: "Follow-up",
    PDFFile: "report_018.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 2
  {
    chartNumber: 2,
    encounterNumber: "E007",
    visitDate: "2024-07-15",
    drFirstName: "David",
    drLastName: "Brown",
    visitType: "Emergency",
    PDFFile: "report_004.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E008",
    visitDate: "2024-07-20",
    drFirstName: "Eve",
    drLastName: "Jones",
    visitType: "Routine Check-up",
    PDFFile: "report_005.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E009",
    visitDate: "2024-07-25",
    drFirstName: "Frank",
    drLastName: "Miller",
    visitType: "Consultation",
    PDFFile: "report_006.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E010",
    visitDate: "2024-08-03",
    drFirstName: "Sarah",
    drLastName: "Wilson",
    visitType: "Consultation",
    PDFFile: "report_019.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E011",
    visitDate: "2024-08-08",
    drFirstName: "James",
    drLastName: "Moore",
    visitType: "Routine Check-up",
    PDFFile: "report_020.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 2,
    encounterNumber: "E012",
    visitDate: "2024-08-14",
    drFirstName: "Olivia",
    drLastName: "Taylor",
    visitType: "Follow-up",
    PDFFile: "report_021.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 3
  {
    chartNumber: 3,
    encounterNumber: "E013",
    visitDate: "2024-06-30",
    drFirstName: "Grace",
    drLastName: "Davis",
    visitType: "Follow-up",
    PDFFile: "report_007.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E014",
    visitDate: "2024-07-05",
    drFirstName: "Henry",
    drLastName: "Wilson",
    visitType: "Emergency",
    PDFFile: "report_008.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E015",
    visitDate: "2024-07-10",
    drFirstName: "Ivy",
    drLastName: "Moore",
    visitType: "Routine Check-up",
    PDFFile: "report_009.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E016",
    visitDate: "2024-08-04",
    drFirstName: "William",
    drLastName: "Anderson",
    visitType: "Initial Consultation",
    PDFFile: "report_022.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E017",
    visitDate: "2024-08-09",
    drFirstName: "Sophia",
    drLastName: "Thomas",
    visitType: "Routine Check-up",
    PDFFile: "report_023.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 3,
    encounterNumber: "E018",
    visitDate: "2024-08-15",
    drFirstName: "David",
    drLastName: "Jackson",
    visitType: "Follow-up",
    PDFFile: "report_024.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 4
  {
    chartNumber: 4,
    encounterNumber: "E019",
    visitDate: "2024-06-01",
    drFirstName: "Jack",
    drLastName: "Taylor",
    visitType: "Consultation",
    PDFFile: "report_010.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E020",
    visitDate: "2024-06-05",
    drFirstName: "Kathy",
    drLastName: "Anderson",
    visitType: "Follow-up",
    PDFFile: "report_011.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E021",
    visitDate: "2024-06-10",
    drFirstName: "Leo",
    drLastName: "Thomas",
    visitType: "Emergency",
    PDFFile: "report_012.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E022",
    visitDate: "2024-08-07",
    drFirstName: "Mia",
    drLastName: "White",
    visitType: "Consultation",
    PDFFile: "report_025.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E023",
    visitDate: "2024-08-11",
    drFirstName: "Ethan",
    drLastName: "Harris",
    visitType: "Routine Check-up",
    PDFFile: "report_026.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 4,
    encounterNumber: "E024",
    visitDate: "2024-08-16",
    drFirstName: "Ava",
    drLastName: "Martin",
    visitType: "Follow-up",
    PDFFile: "report_027.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 5
  {
    chartNumber: 5,
    encounterNumber: "E025",
    visitDate: "2024-05-15",
    drFirstName: "Mia",
    drLastName: "Jackson",
    visitType: "Routine Check-up",
    PDFFile: "report_013.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E026",
    visitDate: "2024-05-20",
    drFirstName: "Nate",
    drLastName: "White",
    visitType: "Consultation",
    PDFFile: "report_014.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E027",
    visitDate: "2024-05-25",
    drFirstName: "Olivia",
    drLastName: "Harris",
    visitType: "Follow-up",
    PDFFile: "report_015.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E028",
    visitDate: "2024-08-09",
    drFirstName: "Liam",
    drLastName: "Lee",
    visitType: "Initial Consultation",
    PDFFile: "report_028.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E029",
    visitDate: "2024-08-13",
    drFirstName: "Isabella",
    drLastName: "García",
    visitType: "Routine Check-up",
    PDFFile: "report_029.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 5,
    encounterNumber: "E030",
    visitDate: "2024-08-18",
    drFirstName: "Noah",
    drLastName: "Rodriguez",
    visitType: "Follow-up",
    PDFFile: "report_030.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 6
  {
    chartNumber: 6,
    encounterNumber: "E031",
    visitDate: "2024-08-01",
    drFirstName: "Emma",
    drLastName: "Clark",
    visitType: "Initial Consultation",
    PDFFile: "report_031.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 6,
    encounterNumber: "E032",
    visitDate: "2024-08-05",
    drFirstName: "Olivia",
    drLastName: "Lopez",
    visitType: "Routine Check-up",
    PDFFile: "report_032.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 6,
    encounterNumber: "E033",
    visitDate: "2024-08-10",
    drFirstName: "Aiden",
    drLastName: "Miller",
    visitType: "Follow-up",
    PDFFile: "report_033.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 6,
    encounterNumber: "E034",
    visitDate: "2024-08-12",
    drFirstName: "Sophia",
    drLastName: "Wilson",
    visitType: "Consultation",
    PDFFile: "report_034.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 6,
    encounterNumber: "E035",
    visitDate: "2024-08-16",
    drFirstName: "Liam",
    drLastName: "Jackson",
    visitType: "Routine Check-up",
    PDFFile: "report_035.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 6,
    encounterNumber: "E036",
    visitDate: "2024-08-20",
    drFirstName: "Isabella",
    drLastName: "Taylor",
    visitType: "Follow-up",
    PDFFile: "report_036.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 7
  {
    chartNumber: 7,
    encounterNumber: "E037",
    visitDate: "2024-08-02",
    drFirstName: "Ethan",
    drLastName: "Davis",
    visitType: "Initial Consultation",
    PDFFile: "report_037.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 7,
    encounterNumber: "E038",
    visitDate: "2024-08-06",
    drFirstName: "Mia",
    drLastName: "Brown",
    visitType: "Routine Check-up",
    PDFFile: "report_038.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 7,
    encounterNumber: "E039",
    visitDate: "2024-08-11",
    drFirstName: "Noah",
    drLastName: "Harris",
    visitType: "Follow-up",
    PDFFile: "report_039.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 7,
    encounterNumber: "E040",
    visitDate: "2024-08-14",
    drFirstName: "Emma",
    drLastName: "Garcia",
    visitType: "Consultation",
    PDFFile: "report_040.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 7,
    encounterNumber: "E041",
    visitDate: "2024-08-18",
    drFirstName: "James",
    drLastName: "Lopez",
    visitType: "Routine Check-up",
    PDFFile: "report_041.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 7,
    encounterNumber: "E042",
    visitDate: "2024-08-22",
    drFirstName: "Ava",
    drLastName: "Miller",
    visitType: "Follow-up",
    PDFFile: "report_042.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 8
  {
    chartNumber: 8,
    encounterNumber: "E043",
    visitDate: "2024-08-03",
    drFirstName: "William",
    drLastName: "Martinez",
    visitType: "Initial Consultation",
    PDFFile: "report_043.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 8,
    encounterNumber: "E044",
    visitDate: "2024-08-07",
    drFirstName: "Sophia",
    drLastName: "Rodriguez",
    visitType: "Routine Check-up",
    PDFFile: "report_044.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 8,
    encounterNumber: "E045",
    visitDate: "2024-08-13",
    drFirstName: "Lucas",
    drLastName: "Lopez",
    visitType: "Follow-up",
    PDFFile: "report_045.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 8,
    encounterNumber: "E046",
    visitDate: "2024-08-15",
    drFirstName: "Olivia",
    drLastName: "Gonzalez",
    visitType: "Consultation",
    PDFFile: "report_046.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 8,
    encounterNumber: "E047",
    visitDate: "2024-08-19",
    drFirstName: "Ethan",
    drLastName: "Walker",
    visitType: "Routine Check-up",
    PDFFile: "report_047.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 8,
    encounterNumber: "E048",
    visitDate: "2024-08-23",
    drFirstName: "Ava",
    drLastName: "Hall",
    visitType: "Follow-up",
    PDFFile: "report_048.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 9
  {
    chartNumber: 9,
    encounterNumber: "E049",
    visitDate: "2024-08-04",
    drFirstName: "Noah",
    drLastName: "Young",
    visitType: "Initial Consultation",
    PDFFile: "report_049.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 9,
    encounterNumber: "E050",
    visitDate: "2024-08-08",
    drFirstName: "Emma",
    drLastName: "Allen",
    visitType: "Routine Check-up",
    PDFFile: "report_050.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 9,
    encounterNumber: "E051",
    visitDate: "2024-08-12",
    drFirstName: "Liam",
    drLastName: "Scott",
    visitType: "Follow-up",
    PDFFile: "report_051.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 9,
    encounterNumber: "E052",
    visitDate: "2024-08-17",
    drFirstName: "Olivia",
    drLastName: "Adams",
    visitType: "Consultation",
    PDFFile: "report_052.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 9,
    encounterNumber: "E053",
    visitDate: "2024-08-20",
    drFirstName: "Ethan",
    drLastName: "Baker",
    visitType: "Routine Check-up",
    PDFFile: "report_053.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 9,
    encounterNumber: "E054",
    visitDate: "2024-08-25",
    drFirstName: "Sophia",
    drLastName: "Nelson",
    visitType: "Follow-up",
    PDFFile: "report_054.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },

  // Chart Number 10
  {
    chartNumber: 10,
    encounterNumber: "E055",
    visitDate: "2024-08-05",
    drFirstName: "James",
    drLastName: "White",
    visitType: "Initial Consultation",
    PDFFile: "report_055.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 10,
    encounterNumber: "E056",
    visitDate: "2024-08-09",
    drFirstName: "Ava",
    drLastName: "Green",
    visitType: "Routine Check-up",
    PDFFile: "report_056.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 10,
    encounterNumber: "E057",
    visitDate: "2024-08-14",
    drFirstName: "Lucas",
    drLastName: "Harris",
    visitType: "Follow-up",
    PDFFile: "report_057.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 10,
    encounterNumber: "E058",
    visitDate: "2024-08-18",
    drFirstName: "Emma",
    drLastName: "Thompson",
    visitType: "Consultation",
    PDFFile: "report_058.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 10,
    encounterNumber: "E059",
    visitDate: "2024-08-22",
    drFirstName: "Ethan",
    drLastName: "King",
    visitType: "Routine Check-up",
    PDFFile: "report_059.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
  {
    chartNumber: 10,
    encounterNumber: "E060",
    visitDate: "2024-08-26",
    drFirstName: "Sophia",
    drLastName: "Wright",
    visitType: "Follow-up",
    PDFFile: "report_060.pdf",
    base64Blob: "data:application/pdf;base64,...",
  },
];
