export const visitsDate = [
  {
    chartNumber: 1,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 1,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 1,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 2,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 2,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 2,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 3,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 3,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 3,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 4,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 4,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 4,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 5,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 5,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
  {
    chartNumber: 5,
    encounterNumber: "",
    visitDate: "",
    drFirstName: "",
    drLastName: "",
    visitType: "",
    PDFFile: "",
    base64Blob: "",
  },
];
